export type PythonTask = {
  starter: string;
  hint: string;
  output: string;
  checks: string[];
  validate: (code: string) => boolean[];
};

const lines = (...parts: string[]) => parts.join("\n");
const task = (starter: string, hint: string, output: string, checks: string[], validate: PythonTask["validate"]): PythonTask => ({ starter, hint, output, checks, validate });

export const pythonTaskGroups: PythonTask[][] = [
  [
    task("# Write your first command below", `print("Hello, Python!")`, "Hello, Python!", ["print(...) is used", "The exact text is inside matching quotes", "The closing parenthesis is present"], code => [/\bprint\s*\(/.test(code), /print\s*\(\s*[\"']Hello, Python![\"']\s*\)/.test(code), /\)\s*$/.test(code.trim())]),
    task("# Print a welcome message", `print("Welcome to the park")`, "Welcome to the park", ["print(...) is used", "The exact phrase is quoted", "The command is complete"], code => [/\bprint\s*\(/.test(code), /[\"']Welcome to the park[\"']/.test(code), /print\s*\([\s\S]*\)/.test(code)]),
    task("# Print text and then a number", `print("Score:", 10)`, "Score: 10", ["Text and number are passed to print", "10 is a number without quotes", "A comma separates the values"], code => [/print\s*\(\s*[\"']Score:[\"']\s*,\s*10\s*\)/.test(code), !/[\"']10[\"']/.test(code), /,/.test(code)]),
    task("# Print two lines with one command", `print("Line 1\\nLine 2")`, lines("Line 1", "Line 2"), ["print(...) is used", "The newline escape \\n is inside the string", "Both phrases are present"], code => [/\bprint\s*\(/.test(code), /[\"']Line 1\\nLine 2[\"']/.test(code), /Line 1/.test(code) && /Line 2/.test(code)]),
    task("# Write two print commands", lines(`print("A")`, `print("B")`), lines("A", "B"), ["Two print commands are used", "The first prints A", "The second prints B"], code => [(code.match(/\bprint\s*\(/g) || []).length >= 2, /print\s*\(\s*[\"']A[\"']\s*\)/.test(code), /print\s*\(\s*[\"']B[\"']\s*\)/.test(code)]),
    task("# Print the number 42", `print(42)`, "42", ["print(...) is used", "42 is inside the parentheses", "42 is written without quotes"], code => [/\bprint\s*\(/.test(code), /print\s*\(\s*42\s*\)/.test(code), !/[\"']42[\"']/.test(code)]),
    task("# Let Python calculate the answer", `print(2 + 3)`, "5", ["print(...) is used", "The expression 2 + 3 is present", "The answer is not hard-coded"], code => [/\bprint\s*\(/.test(code), /2\s*\+\s*3/.test(code), !/print\s*\(\s*5\s*\)/.test(code)]),
    task("# Control the separator", `print("red", "blue", sep="-")`, "red-blue", ["Two text values are printed", "sep is set to a hyphen", "The arguments are comma-separated"], code => [/print\s*\(\s*[\"']red[\"']\s*,\s*[\"']blue[\"']/.test(code), /sep\s*=\s*[\"']-[\"']/.test(code), /,/.test(code)]),
    task("# Keep the cursor on the same line", lines(`print("Loading", end="...")`, `print("done")`), "Loading...done", ["The first print has an end argument", "end contains three dots", "A second print outputs done"], code => [/print\s*\(\s*[\"']Loading[\"']\s*,\s*end\s*=/.test(code), /end\s*=\s*[\"']\.\.\.[\"']/.test(code), /print\s*\(\s*[\"']done[\"']\s*\)/.test(code)]),
    task("# Build a tiny complete script", lines(`name = "Alex"`, `print(f"Hello, {name}!")`), "Hello, Alex!", ["name stores the text Alex", "An f-string is used", "{name} is inserted into the message"], code => [/name\s*=\s*[\"']Alex[\"']/.test(code), /print\s*\(\s*f[\"']/.test(code), /\{name\}/.test(code)]),
  ],
  [
    task("# Create and print an integer", lines("age = 20", "print(age)"), "20", ["age is assigned 20", "The value is a number", "age is printed"], code => [/\bage\s*=\s*20\b/.test(code), !/age\s*=\s*[\"']20[\"']/.test(code), /print\s*\(\s*age\s*\)/.test(code)]),
    task("# Create and print a decimal number", lines("price = 4.5", "print(price)"), "4.5", ["price is assigned 4.5", "The decimal is not quoted", "price is printed"], code => [/\bprice\s*=\s*4\.5\b/.test(code), !/price\s*=\s*[\"']4\.5[\"']/.test(code), /print\s*\(\s*price\s*\)/.test(code)]),
    task("# Create and print a Boolean", lines("is_open = True", "print(is_open)"), "True", ["is_open is assigned True", "True starts with a capital letter", "is_open is printed"], code => [/\bis_open\s*=\s*True\b/.test(code), !/\btrue\b/.test(code), /print\s*\(\s*is_open\s*\)/.test(code)]),
    task("# Store text in a variable", lines(`name = "Maya"`, "print(name)"), "Maya", ["name stores the text Maya", "The text is quoted", "name is printed"], code => [/\bname\s*=\s*[\"']Maya[\"']/.test(code), /[\"']Maya[\"']/.test(code), /print\s*\(\s*name\s*\)/.test(code)]),
    task("# Change an existing value", lines("score = 10", "score = 15", "print(score)"), "15", ["score first receives 10", "score is reassigned to 15", "The new value is printed"], code => [/score\s*=\s*10/.test(code), /score\s*=\s*15/.test(code), /print\s*\(\s*score\s*\)/.test(code)]),
    task("# Find the data type", lines("tickets = 3", "print(type(tickets))"), "<class 'int'>", ["tickets is assigned 3", "type(...) inspects tickets", "The result of type is printed"], code => [/tickets\s*=\s*3/.test(code), /type\s*\(\s*tickets\s*\)/.test(code), /print\s*\(\s*type/.test(code)]),
    task("# Add two variables", lines("a = 7", "b = 5", "print(a + b)"), "12", ["a and b are created", "The + operator joins them in an expression", "The expression is printed"], code => [/a\s*=\s*7/.test(code) && /b\s*=\s*5/.test(code), /a\s*\+\s*b/.test(code), /print\s*\(\s*a\s*\+\s*b\s*\)/.test(code)]),
    task("# Divide two values", lines("total = 10.0", "count = 4", "print(total / count)"), "2.5", ["total and count are created", "The / operator divides them", "The result is printed"], code => [/total\s*=\s*10(?:\.0)?/.test(code) && /count\s*=\s*4/.test(code), /total\s*\/\s*count/.test(code), /print\s*\(\s*total\s*\/\s*count\s*\)/.test(code)]),
    task("# Convert text to a number", lines(`visitors_text = "12"`, "visitors = int(visitors_text)", "print(visitors + 1)"), "13", ["The original value is text", "int(...) converts it", "The converted number is used in addition"], code => [/visitors_text\s*=\s*[\"']12[\"']/.test(code), /visitors\s*=\s*int\s*\(\s*visitors_text\s*\)/.test(code), /print\s*\(\s*visitors\s*\+\s*1\s*\)/.test(code)]),
    task("# Combine variables in an f-string", lines(`ride = "Python Coaster"`, "seats = 24", `print(f"{ride}: {seats} seats")`), "Python Coaster: 24 seats", ["ride and seats are created", "The string starts with f", "Both variables appear inside braces"], code => [/ride\s*=\s*[\"']Python Coaster[\"']/.test(code) && /seats\s*=\s*24/.test(code), /print\s*\(\s*f[\"']/.test(code), /\{ride\}/.test(code) && /\{seats\}/.test(code)]),
  ],
  [
    task(lines("age = 20", "# Add an if statement"), lines("if age >= 18:", `    print("Adult")`), "Adult", ["if checks age >= 18", "The condition ends with a colon", "The print line is indented"], code => [/if\s+age\s*>=\s*18\s*:/.test(code), /if[^\n]*:\s*(?:#.*\n)?\s+print/.test(code), /\n[ \t]+print\s*\(\s*[\"']Adult[\"']/.test(code)]),
    task(lines("score = 65", "# Add if and else"), lines("if score >= 50:", `    print("Pass")`, "else:", `    print("Fail")`), "Pass", ["if checks the score", "else is present and ends with a colon", "Both branches are indented"], code => [/if\s+score\s*>=\s*50\s*:/.test(code), /else\s*:/.test(code), /\n[ \t]+print\s*\(\s*[\"']Pass[\"']/.test(code) && /\n[ \t]+print\s*\(\s*[\"']Fail[\"']/.test(code)]),
    task(lines("secret = 7", "# Check equality"), lines("if secret == 7:", `    print("Correct")`), "Correct", ["== compares two values", "The condition ends with a colon", "Correct is printed in the block"], code => [/secret\s*==\s*7/.test(code), /if[^\n]*:\s*$/.test(code.split("\n").find(line => /if\s+secret/.test(line)) || ""), /\n[ \t]+print\s*\(\s*[\"']Correct[\"']/.test(code)]),
    task(lines("age = 14", "height = 150", "# Check both conditions"), lines("if age >= 12 and height >= 140:", `    print("Allowed")`), "Allowed", ["The first comparison checks age", "and joins the second comparison", "The print line is inside the if block"], code => [/age\s*>=\s*12/.test(code), /\band\s+height\s*>=\s*140/.test(code), /\n[ \t]+print\s*\(\s*[\"']Allowed[\"']/.test(code)]),
    task("# Print car numbers 1 through 3", lines("for car in range(1, 4):", "    print(car)"), lines("1", "2", "3"), ["for uses the variable car", "range(1, 4) produces 1, 2, 3", "The print line is indented"], code => [/for\s+car\s+in\s+range\s*\(\s*1\s*,\s*4\s*\)\s*:/.test(code), /range\s*\(\s*1\s*,\s*4\s*\)/.test(code), /\n[ \t]+print\s*\(\s*car\s*\)/.test(code)]),
    task("# Print 0 through 4", lines("for i in range(5):", "    print(i)"), lines("0", "1", "2", "3", "4"), ["for uses i", "range(5) is used", "i is printed inside the loop"], code => [/for\s+i\s+in\s+range\s*\(\s*5\s*\)\s*:/.test(code), /range\s*\(\s*5\s*\)/.test(code), /\n[ \t]+print\s*\(\s*i\s*\)/.test(code)]),
    task(lines("count = 0", "# Add a while loop"), lines("while count < 3:", "    print(count)", "    count += 1"), lines("0", "1", "2"), ["while checks count < 3", "count is printed in the block", "count increases so the loop can end"], code => [/while\s+count\s*<\s*3\s*:/.test(code), /\n[ \t]+print\s*\(\s*count\s*\)/.test(code), /count\s*\+=\s*1/.test(code)]),
    task(lines("total = 0", "# Add numbers 1 through 5"), lines("for number in range(1, 6):", "    total += number", "print(total)"), "15", ["range includes 1 through 5", "Each number is added to total", "total is printed after the loop"], code => [/range\s*\(\s*1\s*,\s*6\s*\)/.test(code), /total\s*\+=\s*number/.test(code), /(?:^|\n)print\s*\(\s*total\s*\)/.test(code)]),
    task("# Skip the number 3", lines("for i in range(1, 6):", "    if i == 3:", "        continue", "    print(i)"), lines("1", "2", "4", "5"), ["The loop covers 1 through 5", "if detects 3 and continue skips it", "The remaining values are printed"], code => [/range\s*\(\s*1\s*,\s*6\s*\)/.test(code), /if\s+i\s*==\s*3\s*:[\s\S]*?continue/.test(code), /\n[ \t]+print\s*\(\s*i\s*\)/.test(code)]),
    task("# Count down from 3", lines("for count in range(3, 0, -1):", "    print(count)"), lines("3", "2", "1"), ["range starts at 3", "The stop is 0 and the step is -1", "count is printed in the loop"], code => [/range\s*\(\s*3\s*,\s*0\s*,\s*-1\s*\)/.test(code), /-1/.test(code), /\n[ \t]+print\s*\(\s*count\s*\)/.test(code)]),
  ],
  [
    task("# Create greet above the call\n\ngreet()", lines("def greet():", `    print("Hi")`), "Hi", ["def creates greet", "The header ends with a colon", "The function body is indented"], code => [/def\s+greet\s*\(\s*\)\s*:/.test(code), /def[^\n]*:\s*(?:#.*\n)?\s+print/.test(code), /\n[ \t]+print\s*\(\s*[\"']Hi[\"']/.test(code)]),
    task("# Create greet above the call\n\ngreet(\"Alex\")", lines("def greet(name):", "    print(name)"), "Alex", ["greet has a name parameter", "The function prints name", "The existing call passes Alex"], code => [/def\s+greet\s*\(\s*name\s*\)\s*:/.test(code), /\n[ \t]+print\s*\(\s*name\s*\)/.test(code), /greet\s*\(\s*[\"']Alex[\"']\s*\)/.test(code)]),
    task("# Create double_number above the call\n\nprint(double_number(4))", lines("def double_number(number):", "    return number * 2"), "8", ["The function receives number", "return sends back number * 2", "The call uses 4"], code => [/def\s+double_number\s*\(\s*number\s*\)\s*:/.test(code), /return\s+number\s*\*\s*2/.test(code), /double_number\s*\(\s*4\s*\)/.test(code)]),
    task("# Create add above the call\n\nprint(add(3, 5))", lines("def add(a, b):", "    return a + b"), "8", ["add has two parameters", "return adds a and b", "The call passes 3 and 5"], code => [/def\s+add\s*\(\s*a\s*,\s*b\s*\)\s*:/.test(code), /return\s+a\s*\+\s*b/.test(code), /add\s*\(\s*3\s*,\s*5\s*\)/.test(code)]),
    task("# Create is_adult above the call\n\nprint(is_adult(20))", lines("def is_adult(age):", "    return age >= 18"), "True", ["The function receives age", "A Boolean comparison is returned", "The call uses age 20"], code => [/def\s+is_adult\s*\(\s*age\s*\)\s*:/.test(code), /return\s+age\s*>=\s*18/.test(code), /is_adult\s*\(\s*20\s*\)/.test(code)]),
    task("# Create square and store its result", lines("def square(value):", "    return value * value", "", "result = square(6)", "print(result)"), "36", ["square returns value * value", "square(6) is stored in result", "result is printed"], code => [/def\s+square\s*\(\s*value\s*\)[\s\S]*return\s+value\s*\*\s*value/.test(code), /result\s*=\s*square\s*\(\s*6\s*\)/.test(code), /print\s*\(\s*result\s*\)/.test(code)]),
    task("# Add a default value", lines(`def greet(name="Guest"):`, `    print(f"Hello, {name}!")`, "", "greet()"), "Hello, Guest!", ["name has the default Guest", "The f-string inserts name", "greet is called without an argument"], code => [/def\s+greet\s*\(\s*name\s*=\s*[\"']Guest[\"']\s*\)\s*:/.test(code), /f[\"'][^\n]*\{name\}/.test(code), /greet\s*\(\s*\)/.test(code)]),
    task("# Create text_length above the call\n\nprint(text_length(\"Python\"))", lines("def text_length(text):", "    return len(text)"), "6", ["The function receives text", "len(text) is returned", "The existing call uses Python"], code => [/def\s+text_length\s*\(\s*text\s*\)\s*:/.test(code), /return\s+len\s*\(\s*text\s*\)/.test(code), /text_length\s*\(\s*[\"']Python[\"']\s*\)/.test(code)]),
    task("# Reuse add inside add_three", lines("def add(a, b):", "    return a + b", "", "def add_three(a, b, c):", "    return add(add(a, b), c)", "", "print(add_three(1, 2, 3))"), "6", ["add_three has three parameters", "It reuses the add function", "The call uses 1, 2 and 3"], code => [/def\s+add_three\s*\(\s*a\s*,\s*b\s*,\s*c\s*\)\s*:/.test(code), /return\s+add\s*\(\s*add\s*\(\s*a\s*,\s*b\s*\)\s*,\s*c\s*\)/.test(code), /add_three\s*\(\s*1\s*,\s*2\s*,\s*3\s*\)/.test(code)]),
    task("# Complete the park function", lines("def seats_left(total, occupied):", "    return total - occupied", "", "print(seats_left(24, 19))"), "5", ["The function has two parameters", "It returns total - occupied", "The result of 24 and 19 is printed"], code => [/def\s+seats_left\s*\(\s*total\s*,\s*occupied\s*\)\s*:/.test(code), /return\s+total\s*-\s*occupied/.test(code), /print\s*\(\s*seats_left\s*\(\s*24\s*,\s*19\s*\)\s*\)/.test(code)]),
  ],
  [
    task("# Create and print a list", lines(`rides = ["Coaster", "Wheel", "Boats"]`, "print(rides)"), "['Coaster', 'Wheel', 'Boats']", ["A list is stored in rides", "Three quoted items are comma-separated", "rides is printed"], code => [/rides\s*=\s*\[/.test(code), /[\"']Coaster[\"']\s*,\s*[\"']Wheel[\"']\s*,\s*[\"']Boats[\"']/.test(code), /print\s*\(\s*rides\s*\)/.test(code)]),
    task("# Print the first list item", lines(`rides = ["Coaster", "Wheel", "Boats"]`, "print(rides[0])"), "Coaster", ["rides is a list", "Index 0 selects the first item", "The selected item is printed"], code => [/rides\s*=\s*\[/.test(code), /rides\s*\[\s*0\s*\]/.test(code), /print\s*\(\s*rides\s*\[\s*0\s*\]\s*\)/.test(code)]),
    task("# Add an item to the list", lines(`rides = ["Coaster"]`, `rides.append("Wheel")`, "print(rides)"), "['Coaster', 'Wheel']", ["rides starts with Coaster", "append adds Wheel", "The updated list is printed"], code => [/rides\s*=\s*\[\s*[\"']Coaster[\"']\s*\]/.test(code), /rides\.append\s*\(\s*[\"']Wheel[\"']\s*\)/.test(code), /print\s*\(\s*rides\s*\)/.test(code)]),
    task("# Count list items", lines("scores = [8, 10, 7, 9]", "print(len(scores))"), "4", ["scores contains four numbers", "len(scores) counts them", "The count is printed"], code => [/scores\s*=\s*\[\s*8\s*,\s*10\s*,\s*7\s*,\s*9\s*\]/.test(code), /len\s*\(\s*scores\s*\)/.test(code), /print\s*\(\s*len/.test(code)]),
    task("# Add all list values", lines("scores = [8, 10, 7]", "print(sum(scores))"), "25", ["scores contains the required numbers", "sum(scores) adds the values", "The sum is printed"], code => [/scores\s*=\s*\[\s*8\s*,\s*10\s*,\s*7\s*\]/.test(code), /sum\s*\(\s*scores\s*\)/.test(code), /print\s*\(\s*sum/.test(code)]),
    task("# Loop through a list", lines(`rides = ["Coaster", "Wheel"]`, "for ride in rides:", "    print(ride)"), lines("Coaster", "Wheel"), ["for reads each ride from rides", "The loop header ends with a colon", "ride is printed in the indented block"], code => [/for\s+ride\s+in\s+rides\s*:/.test(code), /for[^\n]*:\s*$/.test(code.split("\n").find(line => /for\s+ride/.test(line)) || ""), /\n[ \t]+print\s*\(\s*ride\s*\)/.test(code)]),
    task("# Read a dictionary value", lines(`ride = {"name": "Python Coaster", "seats": 24}`, `print(ride["name"])`), "Python Coaster", ["ride is a dictionary with name and seats", "The key name is used in brackets", "The selected value is printed"], code => [/ride\s*=\s*\{/.test(code) && /[\"']name[\"']\s*:/.test(code), /ride\s*\[\s*[\"']name[\"']\s*\]/.test(code), /print\s*\(/.test(code)]),
    task("# Update a dictionary", lines(`ride = {"seats": 24}`, `ride["seats"] = 30`, `print(ride["seats"])`), "30", ["ride starts with 24 seats", "The seats key is updated to 30", "The updated value is printed"], code => [/[\"']seats[\"']\s*:\s*24/.test(code), /ride\s*\[\s*[\"']seats[\"']\s*\]\s*=\s*30/.test(code), /print\s*\(\s*ride\s*\[\s*[\"']seats[\"']/.test(code)]),
    task("# Check list membership", lines(`rides = ["Coaster", "Wheel"]`, `if "Wheel" in rides:`, `    print("Found")`), "Found", ["in checks whether Wheel is in rides", "The if header ends with a colon", "Found is printed in the block"], code => [/[\"']Wheel[\"']\s+in\s+rides/.test(code), /if[^\n]*:\s*$/.test(code.split("\n").find(line => /^\s*if/.test(line)) || ""), /\n[ \t]+print\s*\(\s*[\"']Found[\"']/.test(code)]),
    task("# Build a list with a comprehension", lines("numbers = [1, 2, 3, 4]", "squares = [number * number for number in numbers]", "print(squares)"), "[1, 4, 9, 16]", ["numbers contains 1 through 4", "The comprehension loops through numbers", "Each number is multiplied by itself"], code => [/numbers\s*=\s*\[\s*1\s*,\s*2\s*,\s*3\s*,\s*4\s*\]/.test(code), /\[\s*number\s*\*\s*number\s+for\s+number\s+in\s+numbers\s*\]/.test(code), /print\s*\(\s*squares\s*\)/.test(code)]),
  ],
  [
    task("# Create a class and use its method", lines("class Greeter:", "    def say_hi(self):", `        print("Hi")`, "", "greeter = Greeter()", "greeter.say_hi()"), "Hi", ["class Greeter ends with a colon", "say_hi receives self", "The method is called on an object"], code => [/class\s+Greeter\s*:/.test(code), /def\s+say_hi\s*\(\s*self\s*\)\s*:/.test(code), /greeter\.say_hi\s*\(\s*\)/.test(code)]),
    task("# Store data in an object", lines("class Ride:", "    def __init__(self, name):", "        self.name = name", "", `ride = Ride("Python Coaster")`, "print(ride.name)"), "Python Coaster", ["__init__ receives self and name", "self.name stores the value", "ride.name is printed"], code => [/def\s+__init__\s*\(\s*self\s*,\s*name\s*\)\s*:/.test(code), /self\.name\s*=\s*name/.test(code), /print\s*\(\s*ride\.name\s*\)/.test(code)]),
    task("# Add a method that returns data", lines("class Ride:", "    def __init__(self, seats):", "        self.seats = seats", "", "    def capacity(self):", "        return self.seats", "", "ride = Ride(24)", "print(ride.capacity())"), "24", ["The constructor stores seats", "capacity receives self", "capacity returns self.seats"], code => [/self\.seats\s*=\s*seats/.test(code), /def\s+capacity\s*\(\s*self\s*\)\s*:/.test(code), /return\s+self\.seats/.test(code)]),
    task("# Change object state with a method", lines("class Counter:", "    def __init__(self):", "        self.value = 0", "", "    def increment(self):", "        self.value += 1", "", "counter = Counter()", "counter.increment()", "print(counter.value)"), "1", ["value starts at 0", "increment adds 1 to self.value", "The method is called before printing"], code => [/self\.value\s*=\s*0/.test(code), /self\.value\s*\+=\s*1/.test(code), /counter\.increment\s*\(\s*\)[\s\S]*print\s*\(\s*counter\.value/.test(code)]),
    task("# Add a setter method", lines("class Ride:", "    def __init__(self, speed):", "        self.speed = speed", "", "    def set_speed(self, speed):", "        self.speed = speed", "", "ride = Ride(10)", "ride.set_speed(30)", "print(ride.speed)"), "30", ["The constructor stores speed", "set_speed updates self.speed", "The method changes the value to 30"], code => [/def\s+set_speed\s*\(\s*self\s*,\s*speed\s*\)\s*:/.test(code), /self\.speed\s*=\s*speed/.test(code), /ride\.set_speed\s*\(\s*30\s*\)/.test(code)]),
    task("# Create two independent objects", lines("class Ride:", "    def __init__(self, speed):", "        self.speed = speed", "", "slow = Ride(10)", "fast = Ride(30)", "print(slow.speed, fast.speed)"), "10 30", ["Ride stores speed", "Two objects receive different values", "Both object values are printed"], code => [/class\s+Ride\s*:[\s\S]*self\.speed\s*=\s*speed/.test(code), /slow\s*=\s*Ride\s*\(\s*10\s*\)[\s\S]*fast\s*=\s*Ride\s*\(\s*30\s*\)/.test(code), /print\s*\(\s*slow\.speed\s*,\s*fast\.speed\s*\)/.test(code)]),
    task("# Add a method with an argument", lines("class Ride:", "    def __init__(self, seats):", "        self.seats = seats", "", "    def seats_left(self, occupied):", "        return self.seats - occupied", "", "ride = Ride(24)", "print(ride.seats_left(19))"), "5", ["The object stores total seats", "seats_left receives occupied", "The method returns the difference"], code => [/self\.seats\s*=\s*seats/.test(code), /def\s+seats_left\s*\(\s*self\s*,\s*occupied\s*\)\s*:/.test(code), /return\s+self\.seats\s*-\s*occupied/.test(code)]),
    task("# Create a Rectangle class", lines("class Rectangle:", "    def __init__(self, width, height):", "        self.width = width", "        self.height = height", "", "    def area(self):", "        return self.width * self.height", "", "rectangle = Rectangle(4, 3)", "print(rectangle.area())"), "12", ["The constructor stores width and height", "area receives self", "area returns width times height"], code => [/self\.width\s*=\s*width/.test(code) && /self\.height\s*=\s*height/.test(code), /def\s+area\s*\(\s*self\s*\)\s*:/.test(code), /return\s+self\.width\s*\*\s*self\.height/.test(code)]),
    task("# Add a readable object description", lines("class Ride:", "    def __init__(self, name):", "        self.name = name", "", "    def __str__(self):", `        return f"Ride: {self.name}"`, "", `ride = Ride("Wheel")`, "print(ride)"), "Ride: Wheel", ["__str__ receives self", "It returns an f-string", "self.name is inserted into the text"], code => [/def\s+__str__\s*\(\s*self\s*\)\s*:/.test(code), /return\s+f[\"']Ride:\s*\{self\.name\}[\"']/.test(code), /print\s*\(\s*ride\s*\)/.test(code)]),
    task("# Build the complete Ride class", lines("class Ride:", "    def __init__(self, name, seats):", "        self.name = name", "        self.seats = seats", "", "    def description(self):", `        return f"{self.name}: {self.seats} seats"`, "", `ride = Ride("Python Coaster", 24)`, "print(ride.description())"), "Python Coaster: 24 seats", ["The constructor stores both fields", "description returns an f-string", "The object method is printed"], code => [/def\s+__init__\s*\(\s*self\s*,\s*name\s*,\s*seats\s*\)/.test(code) && /self\.name\s*=\s*name/.test(code) && /self\.seats\s*=\s*seats/.test(code), /def\s+description\s*\(\s*self\s*\)[\s\S]*return\s+f[\"']/.test(code), /print\s*\(\s*ride\.description\s*\(\s*\)\s*\)/.test(code)]),
  ],
];

export const allPythonTasks = pythonTaskGroups.flat();
