import type { Language } from "../content";

export const pythonTaskGoals: Record<Language, string[][]> = {
  en: [
    ["Print the exact text Hello, Python!.", "Print the text Welcome to the park.", "Print the text Score: and then the number 10 in one print call.", "Print Line 1 and Line 2 on separate lines using \\n.", "Use two separate print calls to output A and B.", "Print the number 42 without quotes.", "Let Python calculate 2 + 3 and print the result.", "Print red and blue with a hyphen separator.", "Print Loading, keep the same line with end=\"...\", then print done.", "Store Alex in name and print Hello, Alex! with an f-string."],
    ["Store the integer 20 in age and print it.", "Store the decimal 4.5 in price and print it.", "Store the Boolean True in is_open and print it.", "Store the text Maya in name and print the variable.", "Set score to 10, change it to 15 and print the new value.", "Use type(...) to print the type of tickets = 3.", "Create a = 7 and b = 5, then print their sum.", "Create total = 10.0 and count = 4, then print total / count.", "Convert the text \"12\" with int(...), add 1 and print 13.", "Create ride and seats, then insert both into an f-string."],
    ["If age is at least 18, print Adult.", "Print Pass when score is at least 50, otherwise print Fail.", "Compare secret with 7 using == and print Correct when equal.", "Print Allowed only when both age and height meet their limits.", "Use for and range(1, 4) to print car from 1 to 3.", "Use range(5) to print i from 0 to 4.", "Use while to print count from 0 to 2 and increase it.", "Add numbers 1 through 5 to total and print 15 after the loop.", "Loop from 1 to 5 and skip 3 with continue.", "Use range(3, 0, -1) to print a countdown."],
    ["Define greet(), print Hi inside it and call it.", "Give greet a name parameter and call it with Alex.", "Define double_number(number) and return number * 2.", "Define add(a, b), return their sum and call it with 3 and 5.", "Define is_adult(age) and return the comparison age >= 18.", "Define square(value), store square(6) in result and print it.", "Give greet a default name of Guest and call it without an argument.", "Define text_length(text) and return len(text).", "Define add_three(a, b, c) by reusing the existing add function.", "Define seats_left(total, occupied), return the difference and print the result."],
    ["Create a list with Coaster, Wheel and Boats, then print it.", "Print the first item of rides using index 0.", "Start with Coaster, append Wheel and print the changed list.", "Count the four values in scores with len(...).", "Add all score values with sum(...).", "Loop through rides and print each ride.", "Create a ride dictionary and print the value stored under the name key.", "Change the seats value from 24 to 30 and print it.", "Use in to check for Wheel and print Found.", "Build a squares list with a list comprehension."],
    ["Create Greeter with say_hi(self), make an object and call the method.", "Create Ride, store name in __init__ and print ride.name.", "Store seats and add capacity(self) that returns the value.", "Create Counter, increment self.value once and print 1.", "Add set_speed(self, speed), change speed to 30 and print it.", "Create two Ride objects with speeds 10 and 30 and print both.", "Add seats_left(self, occupied) and return the remaining seats.", "Create Rectangle and return width * height from area(self).", "Add __str__(self) so printing ride shows Ride: Wheel.", "Build the complete Ride class and print Python Coaster: 24 seats."],
  ],
  ru: [
    ["Выведи точный текст Hello, Python!.", "Выведи текст Welcome to the park.", "Одним вызовом print выведи текст Score: и затем число 10.", "Выведи Line 1 и Line 2 на разных строках с помощью \\n.", "Двумя отдельными вызовами print выведи A и B.", "Выведи число 42 без кавычек.", "Пусть Python вычислит 2 + 3, затем выведи результат.", "Выведи red и blue, задав дефис как разделитель.", "Выведи Loading, оставь курсор в той же строке через end=\"...\", затем выведи done.", "Сохрани Alex в name и выведи Hello, Alex! с помощью f-строки."],
    ["Сохрани целое число 20 в age и выведи его.", "Сохрани дробное число 4.5 в price и выведи его.", "Сохрани логическое значение True в is_open и выведи его.", "Сохрани текст Maya в name и выведи переменную.", "Присвой score значение 10, замени его на 15 и выведи новое значение.", "Через type(...) выведи тип переменной tickets со значением 3.", "Создай a = 7 и b = 5, затем выведи их сумму.", "Создай total = 10.0 и count = 4, затем выведи total / count.", "Преобразуй текст \"12\" через int(...), прибавь 1 и выведи 13.", "Создай ride и seats, затем вставь обе переменные в f-строку."],
    ["Если age не меньше 18, выведи Adult.", "Если score не меньше 50, выведи Pass, иначе выведи Fail.", "Сравни secret с 7 через == и при равенстве выведи Correct.", "Выведи Allowed, только когда age и height одновременно проходят ограничения.", "Через for и range(1, 4) выведи car от 1 до 3.", "Через range(5) выведи i от 0 до 4.", "Через while выведи count от 0 до 2 и увеличивай его.", "Сложи числа от 1 до 5 в total и после цикла выведи 15.", "Перебери числа от 1 до 5 и пропусти 3 с помощью continue.", "Через range(3, 0, -1) выведи обратный отсчёт."],
    ["Определи greet(), внутри выведи Hi и вызови функцию.", "Добавь greet параметр name и вызови функцию со значением Alex.", "Определи double_number(number) и верни number * 2.", "Определи add(a, b), верни сумму и вызови функцию с 3 и 5.", "Определи is_adult(age) и верни результат сравнения age >= 18.", "Определи square(value), сохрани square(6) в result и выведи его.", "Задай для name значение Guest по умолчанию и вызови greet без аргумента.", "Определи text_length(text) и верни len(text).", "Определи add_three(a, b, c), повторно используя готовую функцию add.", "Определи seats_left(total, occupied), верни разность и выведи результат."],
    ["Создай список из Coaster, Wheel и Boats, затем выведи его.", "Выведи первый элемент rides по индексу 0.", "Начни со списка с Coaster, добавь Wheel через append и выведи список.", "Посчитай четыре значения scores через len(...).", "Сложи все значения scores через sum(...).", "Перебери rides циклом и выведи каждый ride.", "Создай словарь ride и выведи значение по ключу name.", "Замени значение seats с 24 на 30 и выведи его.", "Проверь наличие Wheel оператором in и выведи Found.", "Создай список squares с помощью спискового включения."],
    ["Создай Greeter с say_hi(self), объект и вызов метода.", "Создай Ride, сохрани name в __init__ и выведи ride.name.", "Сохрани seats и добавь capacity(self), возвращающий это значение.", "Создай Counter, один раз увеличь self.value и выведи 1.", "Добавь set_speed(self, speed), измени скорость на 30 и выведи её.", "Создай два объекта Ride со скоростями 10 и 30 и выведи обе.", "Добавь seats_left(self, occupied) и верни число свободных мест.", "Создай Rectangle и верни width * height из area(self).", "Добавь __str__(self), чтобы print(ride) вывел Ride: Wheel.", "Собери полный класс Ride и выведи Python Coaster: 24 seats."],
  ],
  uk: [
    ["Виведи точний текст Hello, Python!.", "Виведи текст Welcome to the park.", "Одним викликом print виведи текст Score: і потім число 10.", "Виведи Line 1 і Line 2 в різних рядках за допомогою \\n.", "Двома окремими викликами print виведи A і B.", "Виведи число 42 без лапок.", "Нехай Python обчислить 2 + 3, потім виведи результат.", "Виведи red і blue, задавши дефіс як роздільник.", "Виведи Loading, залиш курсор у тому самому рядку через end=\"...\", потім виведи done.", "Збережи Alex у name і виведи Hello, Alex! за допомогою f-рядка."],
    ["Збережи ціле число 20 в age і виведи його.", "Збережи дробове число 4.5 у price і виведи його.", "Збережи логічне значення True в is_open і виведи його.", "Збережи текст Maya у name і виведи змінну.", "Надай score значення 10, зміни на 15 і виведи нове значення.", "Через type(...) виведи тип змінної tickets зі значенням 3.", "Створи a = 7 і b = 5, потім виведи їхню суму.", "Створи total = 10.0 і count = 4, потім виведи total / count.", "Перетвори текст \"12\" через int(...), додай 1 і виведи 13.", "Створи ride і seats, потім встав обидві змінні у f-рядок."],
    ["Якщо age не менше 18, виведи Adult.", "Якщо score не менше 50, виведи Pass, інакше виведи Fail.", "Порівняй secret із 7 через == і за рівності виведи Correct.", "Виведи Allowed, лише коли age і height одночасно відповідають межам.", "Через for і range(1, 4) виведи car від 1 до 3.", "Через range(5) виведи i від 0 до 4.", "Через while виведи count від 0 до 2 і збільшуй його.", "Додай числа від 1 до 5 у total і після циклу виведи 15.", "Перебери числа від 1 до 5 і пропусти 3 за допомогою continue.", "Через range(3, 0, -1) виведи зворотний відлік."],
    ["Визнач greet(), усередині виведи Hi і виклич функцію.", "Додай greet параметр name і виклич функцію зі значенням Alex.", "Визнач double_number(number) і поверни number * 2.", "Визнач add(a, b), поверни суму й виклич функцію з 3 і 5.", "Визнач is_adult(age) і поверни порівняння age >= 18.", "Визнач square(value), збережи square(6) у result і виведи його.", "Задай для name значення Guest за замовчуванням і виклич greet без аргументу.", "Визнач text_length(text) і поверни len(text).", "Визнач add_three(a, b, c), повторно використавши готову add.", "Визнач seats_left(total, occupied), поверни різницю й виведи результат."],
    ["Створи список із Coaster, Wheel і Boats, потім виведи його.", "Виведи перший елемент rides за індексом 0.", "Почни зі списку з Coaster, додай Wheel через append і виведи список.", "Порахуй чотири значення scores через len(...).", "Додай усі значення scores через sum(...).", "Перебери rides циклом і виведи кожний ride.", "Створи словник ride і виведи значення за ключем name.", "Зміни значення seats з 24 на 30 і виведи його.", "Перевір наявність Wheel оператором in і виведи Found.", "Створи список squares за допомогою спискового включення."],
    ["Створи Greeter із say_hi(self), об’єкт і виклик методу.", "Створи Ride, збережи name в __init__ і виведи ride.name.", "Збережи seats і додай capacity(self), що повертає це значення.", "Створи Counter, один раз збільш self.value і виведи 1.", "Додай set_speed(self, speed), зміни швидкість на 30 і виведи її.", "Створи два об’єкти Ride зі швидкостями 10 і 30 та виведи обидві.", "Додай seats_left(self, occupied) і поверни кількість вільних місць.", "Створи Rectangle і поверни width * height з area(self).", "Додай __str__(self), щоб print(ride) вивів Ride: Wheel.", "Склади повний клас Ride і виведи Python Coaster: 24 seats."],
  ],
  fi: [
    ["Tulosta täsmälleen Hello, Python!.", "Tulosta teksti Welcome to the park.", "Tulosta yhdellä print-kutsulla teksti Score: ja sitten numero 10.", "Tulosta Line 1 ja Line 2 eri riveille käyttäen merkkiä \\n.", "Tulosta A ja B kahdella erillisellä print-kutsulla.", "Tulosta numero 42 ilman lainausmerkkejä.", "Anna Pythonin laskea 2 + 3 ja tulosta tulos.", "Tulosta red ja blue käyttäen yhdysmerkkiä erottimena.", "Tulosta Loading, jatka samaa riviä asetuksella end=\"...\" ja tulosta done.", "Tallenna Alex muuttujaan name ja tulosta Hello, Alex! f-merkkijonolla."],
    ["Tallenna kokonaisluku 20 muuttujaan age ja tulosta se.", "Tallenna desimaali 4.5 muuttujaan price ja tulosta se.", "Tallenna totuusarvo True muuttujaan is_open ja tulosta se.", "Tallenna teksti Maya muuttujaan name ja tulosta muuttuja.", "Aseta score ensin arvoon 10, muuta se arvoon 15 ja tulosta uusi arvo.", "Tulosta muuttujan tickets = 3 tyyppi funktiolla type(...).", "Luo a = 7 ja b = 5 ja tulosta niiden summa.", "Luo total = 10.0 ja count = 4 ja tulosta total / count.", "Muunna teksti \"12\" funktiolla int(...), lisää 1 ja tulosta 13.", "Luo ride ja seats ja lisää molemmat f-merkkijonoon."],
    ["Jos age on vähintään 18, tulosta Adult.", "Tulosta Pass, kun score on vähintään 50, muuten Fail.", "Vertaa secret-arvoa numeroon 7 operaattorilla == ja tulosta Correct.", "Tulosta Allowed vain, kun sekä age että height täyttävät rajat.", "Tulosta car luvusta 1 lukuun 3 käyttäen for ja range(1, 4).", "Tulosta i luvusta 0 lukuun 4 käyttäen range(5).", "Tulosta count luvusta 0 lukuun 2 while-silmukalla ja kasvata sitä.", "Lisää luvut 1–5 muuttujaan total ja tulosta silmukan jälkeen 15.", "Käy luvut 1–5 läpi ja ohita 3 komennolla continue.", "Tulosta lähtölaskenta käyttäen range(3, 0, -1)."],
    ["Määritä greet(), tulosta sen sisällä Hi ja kutsu funktiota.", "Lisää greet-funktiolle name-parametri ja kutsu sitä arvolla Alex.", "Määritä double_number(number) ja palauta number * 2.", "Määritä add(a, b), palauta summa ja kutsu sitä arvoilla 3 ja 5.", "Määritä is_adult(age) ja palauta vertailu age >= 18.", "Määritä square(value), tallenna square(6) muuttujaan result ja tulosta se.", "Anna name-parametrille oletusarvo Guest ja kutsu greet ilman argumenttia.", "Määritä text_length(text) ja palauta len(text).", "Määritä add_three(a, b, c) käyttämällä valmista add-funktiota.", "Määritä seats_left(total, occupied), palauta erotus ja tulosta tulos."],
    ["Luo lista arvoista Coaster, Wheel ja Boats ja tulosta se.", "Tulosta rides-listan ensimmäinen alkio indeksillä 0.", "Aloita arvosta Coaster, lisää Wheel append-metodilla ja tulosta lista.", "Laske scores-listan neljä arvoa funktiolla len(...).", "Laske scores-listan arvot yhteen funktiolla sum(...).", "Käy rides läpi silmukalla ja tulosta jokainen ride.", "Luo ride-sanakirja ja tulosta name-avaimen arvo.", "Muuta seats-arvo 24:stä 30:een ja tulosta se.", "Tarkista Wheel operaattorilla in ja tulosta Found.", "Rakenna squares-lista list comprehension -rakenteella."],
    ["Luo Greeter, jossa on say_hi(self), luo olio ja kutsu metodia.", "Luo Ride, tallenna name metodissa __init__ ja tulosta ride.name.", "Tallenna seats ja lisää sen palauttava capacity(self).", "Luo Counter, kasvata self.value kerran ja tulosta 1.", "Lisää set_speed(self, speed), muuta nopeudeksi 30 ja tulosta se.", "Luo kaksi Ride-oliota nopeuksilla 10 ja 30 ja tulosta molemmat.", "Lisää seats_left(self, occupied) ja palauta vapaat paikat.", "Luo Rectangle ja palauta width * height metodista area(self).", "Lisää __str__(self), jotta print(ride) tulostaa Ride: Wheel.", "Rakenna valmis Ride-luokka ja tulosta Python Coaster: 24 seats."],
  ],
  th: [
    ["แสดงข้อความ Hello, Python! ให้ตรงทุกตัว", "แสดงข้อความ Welcome to the park", "ใช้ print ครั้งเดียวแสดงข้อความ Score: แล้วตามด้วยตัวเลข 10", "แสดง Line 1 และ Line 2 คนละบรรทัดด้วย \\n", "ใช้ print สองคำสั่งแยกกันเพื่อแสดง A และ B", "แสดงตัวเลข 42 โดยไม่ใส่เครื่องหมายคำพูด", "ให้ Python คำนวณ 2 + 3 แล้วแสดงผล", "แสดง red และ blue โดยใช้ขีดกลางเป็นตัวคั่น", "แสดง Loading ต่อบรรทัดเดิมด้วย end=\"...\" แล้วแสดง done", "เก็บ Alex ใน name แล้วใช้ f-string แสดง Hello, Alex!"],
    ["เก็บจำนวนเต็ม 20 ใน age แล้วแสดงค่า", "เก็บทศนิยม 4.5 ใน price แล้วแสดงค่า", "เก็บค่าบูลีน True ใน is_open แล้วแสดงค่า", "เก็บข้อความ Maya ใน name แล้วแสดงตัวแปร", "กำหนด score เป็น 10 เปลี่ยนเป็น 15 แล้วแสดงค่าใหม่", "ใช้ type(...) แสดงชนิดของ tickets = 3", "สร้าง a = 7 และ b = 5 แล้วแสดงผลรวม", "สร้าง total = 10.0 และ count = 4 แล้วแสดง total / count", "แปลงข้อความ \"12\" ด้วย int(...) บวก 1 แล้วแสดง 13", "สร้าง ride และ seats แล้วใส่ทั้งสองตัวแปรใน f-string"],
    ["ถ้า age ไม่น้อยกว่า 18 ให้แสดง Adult", "ถ้า score ไม่น้อยกว่า 50 ให้แสดง Pass ไม่เช่นนั้นแสดง Fail", "เปรียบเทียบ secret กับ 7 ด้วย == แล้วแสดง Correct เมื่อเท่ากัน", "แสดง Allowed เมื่อทั้ง age และ height ผ่านเงื่อนไข", "ใช้ for และ range(1, 4) แสดง car ตั้งแต่ 1 ถึง 3", "ใช้ range(5) แสดง i ตั้งแต่ 0 ถึง 4", "ใช้ while แสดง count ตั้งแต่ 0 ถึง 2 และเพิ่มค่า", "รวมเลข 1 ถึง 5 ใน total แล้วแสดง 15 หลังลูป", "วนเลข 1 ถึง 5 และข้าม 3 ด้วย continue", "ใช้ range(3, 0, -1) แสดงการนับถอยหลัง"],
    ["ประกาศ greet() ให้แสดง Hi ภายใน แล้วเรียกฟังก์ชัน", "เพิ่มพารามิเตอร์ name ให้ greet แล้วเรียกด้วย Alex", "ประกาศ double_number(number) และคืนค่า number * 2", "ประกาศ add(a, b) คืนผลรวม แล้วเรียกด้วย 3 และ 5", "ประกาศ is_adult(age) และคืนผลเปรียบเทียบ age >= 18", "ประกาศ square(value) เก็บ square(6) ใน result แล้วแสดงผล", "กำหนดค่าเริ่มต้นของ name เป็น Guest แล้วเรียก greet โดยไม่ส่งค่า", "ประกาศ text_length(text) และคืนค่า len(text)", "ประกาศ add_three(a, b, c) โดยใช้ฟังก์ชัน add ที่มีอยู่", "ประกาศ seats_left(total, occupied) คืนค่าผลต่าง แล้วแสดงผล"],
    ["สร้างลิสต์ Coaster, Wheel และ Boats แล้วแสดงผล", "แสดงสมาชิกแรกของ rides ด้วยอินเด็กซ์ 0", "เริ่มด้วย Coaster เพิ่ม Wheel ด้วย append แล้วแสดงลิสต์", "นับค่าสี่ค่าใน scores ด้วย len(...)", "รวมค่าทั้งหมดใน scores ด้วย sum(...)", "วนผ่าน rides แล้วแสดง ride แต่ละค่า", "สร้างดิกชันนารี ride แล้วแสดงค่าของคีย์ name", "เปลี่ยนค่า seats จาก 24 เป็น 30 แล้วแสดงผล", "ใช้ in ตรวจ Wheel แล้วแสดง Found", "สร้างลิสต์ squares ด้วย list comprehension"],
    ["สร้าง Greeter พร้อม say_hi(self) สร้างออบเจ็กต์แล้วเรียกเมธอด", "สร้าง Ride เก็บ name ใน __init__ แล้วแสดง ride.name", "เก็บ seats และเพิ่ม capacity(self) ที่คืนค่านั้น", "สร้าง Counter เพิ่ม self.value หนึ่งครั้งแล้วแสดง 1", "เพิ่ม set_speed(self, speed) เปลี่ยนความเร็วเป็น 30 แล้วแสดงผล", "สร้าง Ride สองออบเจ็กต์ด้วยความเร็ว 10 และ 30 แล้วแสดงทั้งคู่", "เพิ่ม seats_left(self, occupied) แล้วคืนจำนวนที่นั่งว่าง", "สร้าง Rectangle แล้วคืน width * height จาก area(self)", "เพิ่ม __str__(self) เพื่อให้ print(ride) แสดง Ride: Wheel", "สร้างคลาส Ride ให้ครบแล้วแสดง Python Coaster: 24 seats"],
  ],
};
