import type { Language } from "./content";

export type SyntaxPart = { code: string; text: string };
export type LessonGuide = { intro: string; syntaxTitle: string; example: string; parts: SyntaxPart[]; remember: string[] };

type AcademyCopy = {
  task: string; of: string; totalTasks: string; chooseTask: string; repetition: string;
  guide: string; remember: string; example: string; hintPattern: string; conceptTitle: string;
  previousTask: string; nextTask: string; taskPassed: string; stagePassed: string;
  genericChecks: string[]; stageProgress: string; allTasks: string;
  outputTitle: string; outputWaiting: string; outputFailed: string; noConsoleOutput: string;
  exitCode: string; outputNote: string;
  diagnosticTitle: string; diagnosticExpected: string; diagnosticInsertion: string;
  diagnosticQuotes: string; diagnosticBraces: string; diagnosticParentheses: string; diagnosticSemicolon: string;
  diagnosticLocation: string; diagnosticMisspelled: string; diagnosticNamespace: string; diagnosticTextQuotes: string;
};

export const academyUi: Record<Language, AcademyCopy> = {
  ru: {
    task: "Задание", of: "из", totalTasks: "упражнений", chooseTask: "Выбери упражнение", repetition: "Сначала повторяем знакомое, затем добавляем только один новый элемент.",
    guide: "ПОДРОБНОЕ ОБЪЯСНЕНИЕ", remember: "Запомни", example: "Разбираем пример", hintPattern: "Подходящая форма кода", conceptTitle: "ПЕРЕД ТЕМ КАК ПИСАТЬ КОД",
    previousTask: "Предыдущее задание", nextTask: "Следующее задание", taskPassed: "Задание выполнено!", stagePassed: "Все 10 заданий этой станции выполнены.",
    genericChecks: ["Использована нужная конструкция", "Значения и операторы указаны верно", "Решение завершено и связано с программой"], stageProgress: "Прогресс станции", allTasks: "заданий выполнено",
    outputTitle: "ВЫВОД ПРОГРАММЫ", outputWaiting: "Нажми «Проверить код», чтобы увидеть результат.", outputFailed: "Вывод не получен. Исправь отмеченные проверки и запусти код ещё раз.", noConsoleOutput: "Программа завершилась без вывода в консоль.", exitCode: "Код завершения", outputNote: "Результат показан после проверки структуры и логики решения.",
    diagnosticTitle: "Что именно нужно исправить:", diagnosticExpected: "Добавь или исправь", diagnosticInsertion: "После std::cout пропущен оператор <<.", diagnosticQuotes: "Количество двойных кавычек не совпадает. Проверь, что каждая строка закрыта.", diagnosticBraces: "Количество открывающих и закрывающих фигурных скобок не совпадает.", diagnosticParentheses: "Количество открывающих и закрывающих круглых скобок не совпадает.", diagnosticSemicolon: "Команда std::cout должна заканчиваться точкой с запятой ;.",
    diagnosticLocation: "Строка {line}, символ {column}", diagnosticMisspelled: "слово `{wrong}` написано неправильно. Напиши `{right}`.", diagnosticNamespace: "после `std` должны стоять два двоеточия `::`.", diagnosticTextQuotes: "текст из нескольких символов нужно писать в двойных кавычках.",
  },
  uk: {
    task: "Завдання", of: "з", totalTasks: "вправ", chooseTask: "Обери вправу", repetition: "Спочатку повторюємо знайоме, потім додаємо лише один новий елемент.",
    guide: "ДОКЛАДНЕ ПОЯСНЕННЯ", remember: "Запам’ятай", example: "Розбираємо приклад", hintPattern: "Відповідна форма коду", conceptTitle: "ПЕРЕД ТИМ ЯК ПИСАТИ КОД",
    previousTask: "Попереднє завдання", nextTask: "Наступне завдання", taskPassed: "Завдання виконано!", stagePassed: "Усі 10 завдань цієї станції виконано.",
    genericChecks: ["Використано потрібну конструкцію", "Значення та оператори вказано правильно", "Розв’язання завершено й пов’язано з програмою"], stageProgress: "Прогрес станції", allTasks: "завдань виконано",
    outputTitle: "ВИВЕДЕННЯ ПРОГРАМИ", outputWaiting: "Натисни «Перевірити код», щоб побачити результат.", outputFailed: "Виведення не отримано. Виправ позначені перевірки та запусти код ще раз.", noConsoleOutput: "Програма завершилася без виведення в консоль.", exitCode: "Код завершення", outputNote: "Результат показано після перевірки структури та логіки розв’язання.",
    diagnosticTitle: "Що саме потрібно виправити:", diagnosticExpected: "Додай або виправ", diagnosticInsertion: "Після std::cout пропущено оператор <<.", diagnosticQuotes: "Кількість подвійних лапок не збігається. Перевір, що кожен рядок закрито.", diagnosticBraces: "Кількість відкривальних і закривальних фігурних дужок не збігається.", diagnosticParentheses: "Кількість відкривальних і закривальних круглих дужок не збігається.", diagnosticSemicolon: "Команда std::cout має завершуватися крапкою з комою ;.",
    diagnosticLocation: "Рядок {line}, символ {column}", diagnosticMisspelled: "слово `{wrong}` написано з помилкою. Напиши `{right}`.", diagnosticNamespace: "після `std` мають стояти дві двокрапки `::`.", diagnosticTextQuotes: "текст із кількох символів потрібно писати в подвійних лапках.",
  },
  fi: {
    task: "Tehtävä", of: "/", totalTasks: "harjoitusta", chooseTask: "Valitse harjoitus", repetition: "Toistamme ensin tutun asian ja lisäämme sitten vain yhden uuden asian.",
    guide: "YKSITYISKOHTAINEN SELITYS", remember: "Muista", example: "Esimerkin rakenne", hintPattern: "Sopiva koodimuoto", conceptTitle: "ENNEN KOODAAMISTA",
    previousTask: "Edellinen tehtävä", nextTask: "Seuraava tehtävä", taskPassed: "Tehtävä suoritettu!", stagePassed: "Kaikki tämän aseman 10 tehtävää on suoritettu.",
    genericChecks: ["Tarvittavaa rakennetta käytetään", "Arvot ja operaattorit ovat oikein", "Ratkaisu on valmis ja liitetty ohjelmaan"], stageProgress: "Aseman edistyminen", allTasks: "tehtävää suoritettu",
    outputTitle: "OHJELMAN TULOSTE", outputWaiting: "Näet tuloksen painamalla Tarkista koodi.", outputFailed: "Tulostetta ei saatu. Korjaa merkityt tarkistukset ja suorita koodi uudelleen.", noConsoleOutput: "Ohjelma päättyi ilman konsolitulostetta.", exitCode: "Paluukoodi", outputNote: "Tulos näytetään ratkaisun rakenteen ja logiikan tarkistuksen jälkeen.",
    diagnosticTitle: "Korjaa nämä kohdat:", diagnosticExpected: "Lisää tai korjaa", diagnosticInsertion: "Operaattori << puuttuu std::cout-kohdan jälkeen.", diagnosticQuotes: "Lainausmerkkien määrä ei täsmää. Tarkista, että jokainen merkkijono on suljettu.", diagnosticBraces: "Avaavien ja sulkevien aaltosulkeiden määrä ei täsmää.", diagnosticParentheses: "Avaavien ja sulkevien kaarisulkeiden määrä ei täsmää.", diagnosticSemicolon: "std::cout-lauseen lopussa pitää olla puolipiste ;.",
    diagnosticLocation: "Rivi {line}, merkki {column}", diagnosticMisspelled: "sana `{wrong}` on kirjoitettu väärin. Kirjoita `{right}`.", diagnosticNamespace: "`std`-sanan jälkeen tarvitaan kaksi kaksoispistettä `::`.", diagnosticTextQuotes: "Usean merkin teksti pitää kirjoittaa lainausmerkkeihin.",
  },
  en: {
    task: "Task", of: "of", totalTasks: "exercises", chooseTask: "Choose an exercise", repetition: "First repeat something familiar, then add just one new element.",
    guide: "DETAILED EXPLANATION", remember: "Remember", example: "Break down the example", hintPattern: "A useful code pattern", conceptTitle: "BEFORE YOU CODE",
    previousTask: "Previous task", nextTask: "Next task", taskPassed: "Task completed!", stagePassed: "All 10 tasks at this station are complete.",
    genericChecks: ["The required construct is used", "Values and operators are correct", "The solution is complete and connected to the program"], stageProgress: "Station progress", allTasks: "tasks completed",
    outputTitle: "PROGRAM OUTPUT", outputWaiting: "Press Check code to see the result.", outputFailed: "No output was produced. Fix the marked checks and run the code again.", noConsoleOutput: "The program finished without console output.", exitCode: "Exit code", outputNote: "The result is shown after the solution structure and logic are validated.",
    diagnosticTitle: "Fix these exact parts:", diagnosticExpected: "Add or correct", diagnosticInsertion: "The << operator is missing after std::cout.", diagnosticQuotes: "The double quotation marks do not match. Check that every string is closed.", diagnosticBraces: "The number of opening and closing braces does not match.", diagnosticParentheses: "The number of opening and closing parentheses does not match.", diagnosticSemicolon: "The std::cout statement must end with a semicolon ;.",
    diagnosticLocation: "Line {line}, character {column}", diagnosticMisspelled: "the word `{wrong}` is misspelled. Write `{right}`.", diagnosticNamespace: "two colons `::` are required after `std`.", diagnosticTextQuotes: "text containing several characters must use double quotation marks.",
  },
  th: {
    task: "โจทย์", of: "จาก", totalTasks: "แบบฝึกหัด", chooseTask: "เลือกแบบฝึกหัด", repetition: "เริ่มจากทบทวนสิ่งที่คุ้นเคย แล้วเพิ่มแนวคิดใหม่ครั้งละหนึ่งอย่าง",
    guide: "คำอธิบายโดยละเอียด", remember: "จำไว้", example: "แยกส่วนตัวอย่าง", hintPattern: "รูปแบบโค้ดที่ใช้ได้", conceptTitle: "ก่อนเขียนโค้ด",
    previousTask: "โจทย์ก่อนหน้า", nextTask: "โจทย์ถัดไป", taskPassed: "ทำโจทย์สำเร็จ!", stagePassed: "ทำโจทย์ทั้ง 10 ข้อของสถานีนี้ครบแล้ว",
    genericChecks: ["ใช้โครงสร้างที่กำหนด", "ค่าและตัวดำเนินการถูกต้อง", "คำตอบสมบูรณ์และเชื่อมต่อกับโปรแกรม"], stageProgress: "ความคืบหน้าของสถานี", allTasks: "โจทย์ที่ทำเสร็จ",
    outputTitle: "ผลลัพธ์ของโปรแกรม", outputWaiting: "กด “ตรวจโค้ด” เพื่อดูผลลัพธ์", outputFailed: "ยังไม่มีผลลัพธ์ แก้รายการที่ไม่ผ่านแล้วตรวจโค้ดอีกครั้ง", noConsoleOutput: "โปรแกรมจบการทำงานโดยไม่มีผลลัพธ์ในคอนโซล", exitCode: "รหัสจบการทำงาน", outputNote: "ผลลัพธ์จะแสดงหลังจากตรวจโครงสร้างและตรรกะของคำตอบแล้ว",
    diagnosticTitle: "ส่วนที่ต้องแก้ไข:", diagnosticExpected: "เพิ่มหรือแก้ไข", diagnosticInsertion: "ขาดตัวดำเนินการ << หลัง std::cout", diagnosticQuotes: "จำนวนเครื่องหมายอัญประกาศคู่ไม่ตรงกัน ตรวจสอบว่าสตริงทุกชุดปิดครบ", diagnosticBraces: "จำนวนวงเล็บปีกกาเปิดและปิดไม่ตรงกัน", diagnosticParentheses: "จำนวนวงเล็บกลมเปิดและปิดไม่ตรงกัน", diagnosticSemicolon: "คำสั่ง std::cout ต้องจบด้วยเครื่องหมายอัฒภาค ;",
    diagnosticLocation: "บรรทัด {line}, อักขระ {column}", diagnosticMisspelled: "คำว่า `{wrong}` สะกดไม่ถูกต้อง ให้เขียนเป็น `{right}`", diagnosticNamespace: "หลัง `std` ต้องมีเครื่องหมายทวิภาคสองตัว `::`", diagnosticTextQuotes: "ข้อความที่มีหลายอักขระต้องอยู่ภายในเครื่องหมายอัญประกาศคู่",
  },
};

export const lessonGuides: Record<Language, LessonGuide[]> = {
  ru: [
    { intro: "Строка вывода состоит из четырёх обязательных частей. Компьютер не догадывается, где текст и где заканчивается команда, поэтому каждый знак имеет значение.", syntaxTitle: "Как читается строка вывода", example: `std::cout << "Hello, C++!";`, parts: [{ code: "std::cout", text: "стандартный поток вывода, то есть место, куда отправляем результат" }, { code: "<<", text: "оператор вставки: направляет то, что стоит справа, в поток слева" }, { code: "\"текст\"", text: "кавычки создают строковый литерал, сам текст находится между ними" }, { code: ";", text: "точка с запятой сообщает компилятору, что команда закончена" }], remember: ["Текст всегда заключают в двойные кавычки", "Число можно выводить без кавычек", "Каждую законченную команду закрывает ;", "\\n внутри текста переносит вывод на новую строку"] },
    { intro: "Переменная похожа на подписанную коробку в памяти. При объявлении мы указываем тип коробки, её имя и начальное значение.", syntaxTitle: "Анатомия переменной", example: `int visitors = 24;`, parts: [{ code: "int", text: "тип целого числа" }, { code: "visitors", text: "понятное имя переменной" }, { code: "=", text: "оператор присваивания" }, { code: "24", text: "начальное значение" }, { code: ";", text: "конец инструкции" }], remember: ["int хранит целые числа", "double хранит дробные числа", "bool хранит true или false", "std::string хранит текст и требует <string>"] },
    { intro: "Условие выбирает путь, цикл повторяет путь. Выражение в круглых скобках вычисляется как true или false, а фигурные скобки объединяют выполняемые команды.", syntaxTitle: "Анатомия условия", example: `if (age >= 18) { std::cout << "Adult"; }`, parts: [{ code: "if", text: "начинает проверку условия" }, { code: "(age >= 18)", text: "логическое выражение в круглых скобках" }, { code: "{ ... }", text: "блок выполняется, если условие истинно" }, { code: ">=", text: "сравнивает: больше или равно" }], remember: ["== сравнивает, а = присваивает", "&& означает И, оба условия должны быть истинны", "for удобен для известного числа повторов", "while повторяется, пока условие истинно"] },
    { intro: "Функция получает имя и отдельную задачу. Параметры передают ей данные, тип перед именем описывает результат, а return возвращает этот результат.", syntaxTitle: "Анатомия функции", example: `int add(int a, int b) { return a + b; }`, parts: [{ code: "int", text: "тип возвращаемого результата" }, { code: "add", text: "имя функции" }, { code: "(int a, int b)", text: "два входных параметра" }, { code: "return", text: "возвращает результат вызывающему коду" }], remember: ["void означает отсутствие возвращаемого значения", "Аргументы указывают при вызове функции", "Объявление сообщает о функции заранее", "Небольшие функции легче проверять"] },
    { intro: "Ссылка даёт второе имя существующей переменной. Указатель хранит её адрес. Символы & и * имеют разные роли в зависимости от места, где они написаны.", syntaxTitle: "Ссылка и указатель", example: `int& alias = value;   int* ptr = &value;`, parts: [{ code: "int& alias", text: "alias является ссылкой на int" }, { code: "&value", text: "получает адрес переменной value" }, { code: "int* ptr", text: "ptr является указателем на int" }, { code: "*ptr", text: "разыменование: доступ к значению по адресу" }], remember: ["Изменение ссылки меняет исходную переменную", "nullptr означает отсутствие адреса", "Перед разыменованием указатель нужно проверять", "const ссылка позволяет читать без копирования"] },
    { intro: "Класс создаёт собственный тип данных. private-поля хранят внутреннее состояние, public-методы образуют интерфейс, а конструктор подготавливает новый объект.", syntaxTitle: "Анатомия класса", example: `class Ride { public: Ride(int s) : seats_(s) {} private: int seats_; };`, parts: [{ code: "class Ride", text: "объявляет новый тип Ride" }, { code: "public:", text: "открытая часть интерфейса" }, { code: "Ride(int s)", text: "конструктор вызывается при создании объекта" }, { code: "private:", text: "закрывает внутренние поля от прямого доступа" }], remember: ["После определения класса ставят ;", "Объект создаётся как Ride coaster(24)", "Метод вызывают через точку", "const-метод не изменяет объект"] },
  ],
  uk: [
    { intro: "Рядок виведення складається з чотирьох обов’язкових частин. Комп’ютер не здогадується, де текст і де завершується команда, тому кожен знак має значення.", syntaxTitle: "Як читається рядок виведення", example: `std::cout << "Hello, C++!";`, parts: [{ code: "std::cout", text: "стандартний потік виведення, куди надсилаємо результат" }, { code: "<<", text: "оператор вставки: спрямовує те, що праворуч, у потік ліворуч" }, { code: "\"текст\"", text: "лапки створюють рядковий літерал" }, { code: ";", text: "крапка з комою завершує команду" }], remember: ["Текст завжди беруть у подвійні лапки", "Число можна виводити без лапок", "Кожну завершену команду закриває ;", "\\n усередині тексту переходить на новий рядок"] },
    { intro: "Змінна схожа на підписану коробку в пам’яті. Під час оголошення вказуємо тип, ім’я та початкове значення.", syntaxTitle: "Анатомія змінної", example: `int visitors = 24;`, parts: [{ code: "int", text: "тип цілого числа" }, { code: "visitors", text: "ім’я змінної" }, { code: "=", text: "оператор присвоєння" }, { code: "24", text: "початкове значення" }, { code: ";", text: "кінець інструкції" }], remember: ["int зберігає цілі числа", "double зберігає дробові числа", "bool зберігає true або false", "std::string зберігає текст і потребує <string>"] },
    { intro: "Умова обирає шлях, цикл повторює шлях. Вираз у круглих дужках дає true або false, а фігурні дужки об’єднують команди.", syntaxTitle: "Анатомія умови", example: `if (age >= 18) { std::cout << "Adult"; }`, parts: [{ code: "if", text: "починає перевірку" }, { code: "(age >= 18)", text: "логічний вираз" }, { code: "{ ... }", text: "блок для істинної умови" }, { code: ">=", text: "порівняння: більше або дорівнює" }], remember: ["== порівнює, а = присвоює", "&& означає І", "for зручний для відомої кількості повторів", "while повторюється, доки умова істинна"] },
    { intro: "Функція має ім’я та окреме завдання. Параметри передають дані, тип перед ім’ям описує результат, а return повертає його.", syntaxTitle: "Анатомія функції", example: `int add(int a, int b) { return a + b; }`, parts: [{ code: "int", text: "тип результату" }, { code: "add", text: "ім’я функції" }, { code: "(int a, int b)", text: "два параметри" }, { code: "return", text: "повертає результат" }], remember: ["void означає відсутність результату", "Аргументи вказують під час виклику", "Оголошення повідомляє про функцію заздалегідь", "Малі функції легше перевіряти"] },
    { intro: "Посилання дає друге ім’я наявній змінній. Вказівник зберігає її адресу. Символи & і * мають різні ролі залежно від місця.", syntaxTitle: "Посилання та вказівник", example: `int& alias = value;   int* ptr = &value;`, parts: [{ code: "int& alias", text: "alias є посиланням на int" }, { code: "&value", text: "отримує адресу value" }, { code: "int* ptr", text: "ptr є вказівником на int" }, { code: "*ptr", text: "доступ до значення за адресою" }], remember: ["Зміна посилання змінює початкову змінну", "nullptr означає відсутність адреси", "Вказівник перевіряють перед розіменуванням", "const-посилання читає без копії"] },
    { intro: "Клас створює власний тип. private-поля зберігають внутрішній стан, public-методи утворюють інтерфейс, а конструктор готує об’єкт.", syntaxTitle: "Анатомія класу", example: `class Ride { public: Ride(int s) : seats_(s) {} private: int seats_; };`, parts: [{ code: "class Ride", text: "оголошує новий тип Ride" }, { code: "public:", text: "відкрита частина" }, { code: "Ride(int s)", text: "конструктор" }, { code: "private:", text: "закрита частина даних" }], remember: ["Після визначення класу ставлять ;", "Об’єкт: Ride coaster(24)", "Метод викликають через крапку", "const-метод не змінює об’єкт"] },
  ],
  fi: [
    { intro: "Tulostuslauseessa on neljä pakollista osaa. Tietokone ei arvaa, mikä on tekstiä tai missä komento päättyy, joten jokaisella merkillä on tehtävä.", syntaxTitle: "Tulostuslauseen osat", example: `std::cout << "Hello, C++!";`, parts: [{ code: "std::cout", text: "vakiotulostusvirta, johon tulos lähetetään" }, { code: "<<", text: "syöttöoperaattori ohjaa oikealla olevan asian vasempaan virtaan" }, { code: "\"teksti\"", text: "lainausmerkit muodostavat merkkijonoliteraalin" }, { code: ";", text: "puolipiste päättää lauseen" }], remember: ["Teksti kirjoitetaan lainausmerkkeihin", "Luvun voi tulostaa ilman lainausmerkkejä", "Valmis lause päättyy puolipisteeseen", "\\n siirtää tulostuksen uudelle riville"] },
    { intro: "Muuttuja on kuin nimetty laatikko muistissa. Esittelyssä annetaan laatikon tyyppi, nimi ja alkuarvo.", syntaxTitle: "Muuttujan osat", example: `int visitors = 24;`, parts: [{ code: "int", text: "kokonaislukutyyppi" }, { code: "visitors", text: "muuttujan nimi" }, { code: "=", text: "sijoitusoperaattori" }, { code: "24", text: "alkuarvo" }, { code: ";", text: "lauseen loppu" }], remember: ["int tallentaa kokonaislukuja", "double tallentaa desimaalilukuja", "bool tallentaa true tai false", "std::string tallentaa tekstiä ja tarvitsee <string>"] },
    { intro: "Ehto valitsee reitin ja silmukka toistaa reitin. Sulkeiden lauseke antaa true- tai false-arvon, ja aaltosulkeet kokoavat suoritettavat lauseet.", syntaxTitle: "Ehdon osat", example: `if (age >= 18) { std::cout << "Adult"; }`, parts: [{ code: "if", text: "aloittaa ehdon tarkistuksen" }, { code: "(age >= 18)", text: "totuusarvoinen lauseke" }, { code: "{ ... }", text: "tosi-tilassa suoritettava lohko" }, { code: ">=", text: "suurempi tai yhtä suuri" }], remember: ["== vertaa ja = sijoittaa", "&& tarkoittaa JA", "for sopii tunnettuun toistomäärään", "while jatkuu ehdon ollessa tosi"] },
    { intro: "Funktiolla on nimi ja oma tehtävä. Parametrit tuovat dataa, nimeä edeltävä tyyppi kertoo tuloksen ja return palauttaa sen.", syntaxTitle: "Funktion osat", example: `int add(int a, int b) { return a + b; }`, parts: [{ code: "int", text: "tuloksen tyyppi" }, { code: "add", text: "funktion nimi" }, { code: "(int a, int b)", text: "kaksi parametria" }, { code: "return", text: "palauttaa tuloksen" }], remember: ["void tarkoittaa, ettei arvoa palauteta", "Argumentit annetaan kutsussa", "Esittely kertoo funktiosta etukäteen", "Pieni funktio on helppo testata"] },
    { intro: "Viite antaa olemassa olevalle muuttujalle toisen nimen. Osoitin tallentaa sen osoitteen. Merkeillä & ja * on eri tehtävä eri kohdissa.", syntaxTitle: "Viite ja osoitin", example: `int& alias = value;   int* ptr = &value;`, parts: [{ code: "int& alias", text: "alias on viite int-arvoon" }, { code: "&value", text: "hakee value-muuttujan osoitteen" }, { code: "int* ptr", text: "ptr on int-osoitin" }, { code: "*ptr", text: "hakee arvon osoitteesta" }], remember: ["Viitteen muutos muuttaa alkuperäistä muuttujaa", "nullptr tarkoittaa tyhjää osoitetta", "Osoitin tarkistetaan ennen dereferointia", "const-viite lukee ilman kopiota"] },
    { intro: "Luokka luo uuden tietotyypin. private-kentät säilyttävät sisäisen tilan, public-metodit muodostavat rajapinnan ja konstruktori alustaa olion.", syntaxTitle: "Luokan osat", example: `class Ride { public: Ride(int s) : seats_(s) {} private: int seats_; };`, parts: [{ code: "class Ride", text: "määrittelee uuden Ride-tyypin" }, { code: "public:", text: "julkinen rajapinta" }, { code: "Ride(int s)", text: "konstruktori" }, { code: "private:", text: "suojattu sisäinen data" }], remember: ["Luokan määrittelyn jälkeen tulee ;", "Olio: Ride coaster(24)", "Metodia kutsutaan pisteellä", "const-metodi ei muuta oliota"] },
  ],
  en: [
    { intro: "An output statement has four required parts. The computer cannot guess what is text or where a command ends, so every symbol has a job.", syntaxTitle: "Read an output statement", example: `std::cout << "Hello, C++!";`, parts: [{ code: "std::cout", text: "the standard output stream, where the result is sent" }, { code: "<<", text: "the insertion operator sends the item on the right into the stream on the left" }, { code: "\"text\"", text: "quotes create a string literal" }, { code: ";", text: "the semicolon ends the statement" }], remember: ["Put text inside double quotes", "A number can be printed without quotes", "End every complete statement with ;", "\\n inside text starts a new line"] },
    { intro: "A variable is like a labelled box in memory. A declaration gives the box a type, a name and an initial value.", syntaxTitle: "Anatomy of a variable", example: `int visitors = 24;`, parts: [{ code: "int", text: "the whole-number type" }, { code: "visitors", text: "the variable name" }, { code: "=", text: "the assignment operator" }, { code: "24", text: "the initial value" }, { code: ";", text: "the end of the statement" }], remember: ["int stores whole numbers", "double stores decimal numbers", "bool stores true or false", "std::string stores text and needs <string>"] },
    { intro: "A condition chooses a path, while a loop repeats a path. The expression in parentheses becomes true or false, and braces group the statements to run.", syntaxTitle: "Anatomy of a condition", example: `if (age >= 18) { std::cout << "Adult"; }`, parts: [{ code: "if", text: "starts a condition" }, { code: "(age >= 18)", text: "a Boolean expression" }, { code: "{ ... }", text: "the block that runs when true" }, { code: ">=", text: "compares greater than or equal" }], remember: ["== compares, while = assigns", "&& means AND", "for suits a known number of repetitions", "while repeats as long as its condition is true"] },
    { intro: "A function has a name and one focused job. Parameters bring data in, the type before the name describes the result, and return sends it back.", syntaxTitle: "Anatomy of a function", example: `int add(int a, int b) { return a + b; }`, parts: [{ code: "int", text: "the result type" }, { code: "add", text: "the function name" }, { code: "(int a, int b)", text: "two input parameters" }, { code: "return", text: "sends a result to the caller" }], remember: ["void means no value is returned", "Arguments are supplied in a function call", "A declaration introduces a function early", "Small functions are easier to test"] },
    { intro: "A reference gives an existing variable another name. A pointer stores its address. The symbols & and * have different jobs depending on where they appear.", syntaxTitle: "Reference and pointer", example: `int& alias = value;   int* ptr = &value;`, parts: [{ code: "int& alias", text: "alias is a reference to an int" }, { code: "&value", text: "gets the address of value" }, { code: "int* ptr", text: "ptr is a pointer to an int" }, { code: "*ptr", text: "dereferences the pointer to access the value" }], remember: ["Changing a reference changes the original variable", "nullptr represents no address", "Check a pointer before dereferencing it", "A const reference reads without making a copy"] },
    { intro: "A class creates a new type. Private fields store internal state, public methods form the interface, and a constructor prepares each new object.", syntaxTitle: "Anatomy of a class", example: `class Ride { public: Ride(int s) : seats_(s) {} private: int seats_; };`, parts: [{ code: "class Ride", text: "declares the new Ride type" }, { code: "public:", text: "the visible interface" }, { code: "Ride(int s)", text: "the constructor" }, { code: "private:", text: "protects internal fields" }], remember: ["Put ; after a class definition", "Create an object with Ride coaster(24)", "Call a method with a dot", "A const method does not modify the object"] },
  ],
  th: [
    { intro: "คำสั่งแสดงผลมีส่วนประกอบที่จำเป็นสี่ส่วน คอมพิวเตอร์เดาไม่ได้ว่าส่วนใดเป็นข้อความหรือคำสั่งจบตรงไหน ดังนั้นทุกสัญลักษณ์จึงมีหน้าที่", syntaxTitle: "อ่านส่วนประกอบของคำสั่งแสดงผล", example: `std::cout << "Hello, C++!";`, parts: [{ code: "std::cout", text: "สตรีมเอาต์พุตมาตรฐานซึ่งรับผลลัพธ์ที่เราต้องการแสดง" }, { code: "<<", text: "ตัวดำเนินการแทรก ส่งสิ่งที่อยู่ด้านขวาเข้าสู่สตรีมด้านซ้าย" }, { code: "\"ข้อความ\"", text: "อัญประกาศคู่สร้างสตริง โดยข้อความอยู่ระหว่างอัญประกาศ" }, { code: ";", text: "เครื่องหมายอัฒภาคใช้จบคำสั่ง" }], remember: ["ข้อความต้องอยู่ในอัญประกาศคู่", "ตัวเลขแสดงผลได้โดยไม่ต้องใส่อัญประกาศ", "ทุกคำสั่งที่สมบูรณ์ต้องจบด้วย ;", "\n ภายในข้อความใช้ขึ้นบรรทัดใหม่"] },
    { intro: "ตัวแปรเปรียบเหมือนกล่องที่มีชื่อในหน่วยความจำ ตอนประกาศเราจะกำหนดชนิด ชื่อ และค่าเริ่มต้นให้กล่องนั้น", syntaxTitle: "ส่วนประกอบของตัวแปร", example: `int visitors = 24;`, parts: [{ code: "int", text: "ชนิดข้อมูลจำนวนเต็ม" }, { code: "visitors", text: "ชื่อตัวแปร" }, { code: "=", text: "ตัวดำเนินการกำหนดค่า" }, { code: "24", text: "ค่าเริ่มต้น" }, { code: ";", text: "จบคำสั่ง" }], remember: ["int เก็บจำนวนเต็ม", "double เก็บจำนวนทศนิยม", "bool เก็บ true หรือ false", "std::string เก็บข้อความและต้องใช้ <string>"] },
    { intro: "เงื่อนไขใช้เลือกเส้นทาง ส่วนลูปใช้ทำเส้นทางเดิมซ้ำ นิพจน์ในวงเล็บกลมให้ค่า true หรือ false และวงเล็บปีกการวมคำสั่งที่ต้องทำ", syntaxTitle: "ส่วนประกอบของเงื่อนไข", example: `if (age >= 18) { std::cout << "Adult"; }`, parts: [{ code: "if", text: "เริ่มตรวจเงื่อนไข" }, { code: "(age >= 18)", text: "นิพจน์บูลีนในวงเล็บกลม" }, { code: "{ ... }", text: "บล็อกที่จะทำงานเมื่อเงื่อนไขเป็นจริง" }, { code: ">=", text: "เปรียบเทียบว่ามากกว่าหรือเท่ากับ" }], remember: ["== ใช้เปรียบเทียบ ส่วน = ใช้กำหนดค่า", "&& หมายถึง AND และทั้งสองเงื่อนไขต้องเป็นจริง", "for เหมาะเมื่อรู้จำนวนรอบ", "while ทำซ้ำตราบใดที่เงื่อนไขเป็นจริง"] },
    { intro: "ฟังก์ชันมีชื่อและรับผิดชอบงานหนึ่งอย่าง พารามิเตอร์นำข้อมูลเข้า ชนิดหน้าชื่อบอกชนิดผลลัพธ์ และ return ส่งผลลัพธ์กลับ", syntaxTitle: "ส่วนประกอบของฟังก์ชัน", example: `int add(int a, int b) { return a + b; }`, parts: [{ code: "int", text: "ชนิดของผลลัพธ์" }, { code: "add", text: "ชื่อฟังก์ชัน" }, { code: "(int a, int b)", text: "พารามิเตอร์รับข้อมูลสองตัว" }, { code: "return", text: "ส่งผลลัพธ์กลับไปยังผู้เรียก" }], remember: ["void หมายถึงไม่คืนค่า", "อาร์กิวเมนต์ถูกส่งตอนเรียกฟังก์ชัน", "การประกาศช่วยแนะนำฟังก์ชันล่วงหน้า", "ฟังก์ชันขนาดเล็กทดสอบได้ง่ายกว่า"] },
    { intro: "reference เป็นอีกชื่อหนึ่งของตัวแปรเดิม ส่วน pointer เก็บที่อยู่ของตัวแปร สัญลักษณ์ & และ * มีหน้าที่ต่างกันตามตำแหน่งที่ใช้", syntaxTitle: "Reference และ pointer", example: `int& alias = value;   int* ptr = &value;`, parts: [{ code: "int& alias", text: "alias เป็น reference ไปยัง int" }, { code: "&value", text: "อ่านที่อยู่ของตัวแปร value" }, { code: "int* ptr", text: "ptr เป็น pointer ไปยัง int" }, { code: "*ptr", text: "dereference เพื่อเข้าถึงค่าที่ตำแหน่งนั้น" }], remember: ["การเปลี่ยน reference จะเปลี่ยนตัวแปรต้นฉบับ", "nullptr หมายถึงไม่มีที่อยู่", "ตรวจ pointer ก่อน dereference", "const reference อ่านค่าได้โดยไม่ต้องสร้างสำเนา"] },
    { intro: "คลาสสร้างชนิดข้อมูลใหม่ ฟิลด์ private เก็บสถานะภายใน เมธอด public สร้างอินเทอร์เฟซ และ constructor เตรียมออบเจ็กต์ใหม่", syntaxTitle: "ส่วนประกอบของคลาส", example: `class Ride { public: Ride(int s) : seats_(s) {} private: int seats_; };`, parts: [{ code: "class Ride", text: "ประกาศชนิดข้อมูลใหม่ชื่อ Ride" }, { code: "public:", text: "ส่วนอินเทอร์เฟซที่ภายนอกเรียกใช้ได้" }, { code: "Ride(int s)", text: "constructor ที่ทำงานเมื่อสร้างออบเจ็กต์" }, { code: "private:", text: "ปกป้องฟิลด์ภายในจากการเข้าถึงโดยตรง" }], remember: ["ใส่ ; หลังนิยามคลาส", "สร้างออบเจ็กต์ด้วย Ride coaster(24)", "เรียกเมธอดด้วยเครื่องหมายจุด", "เมธอด const ไม่เปลี่ยนออบเจ็กต์"] },
  ],
};

export const taskInstructions: Record<Language, string[][]> = {
  ru: [
    [
      "Выведи точный текст Hello, C++! с помощью std::cout.",
      "Выведи текст My first program. Не забудь кавычки и точку с запятой.",
      "Одной командой выведи текст Score: и затем число 10, используя два оператора <<.",
      "Выведи Line 1 и Line 2 на разных строках с помощью \\n внутри текста.",
      "Напиши две отдельные команды std::cout: первая выводит A, вторая B.",
      "Выведи число 42 без кавычек. Оно должно быть числом, а не текстом.",
      "Выведи результат выражения 2 + 3. Не вычисляй его заранее вручную.",
      "Соедини текст Cars: и число 3 в одной команде std::cout.",
      "Выведи Ready и заверши строку с помощью std::endl.",
      "С пустого места собери полную программу, которая выводит I can code!.",
    ],
    [
      "Создай целочисленную переменную age со значением 20 и выведи её.",
      "Создай дробную переменную price со значением 4.5 и выведи её.",
      "Создай логическую переменную open со значением true и выведи её.",
      "Создай std::string name со значением Alex и выведи name.",
      "Создай score со значением 10, затем присвой 15 и выведи новое значение.",
      "Создай константу seats со значением 24 и выведи её.",
      "Создай a = 7 и b = 5, затем выведи сумму a + b.",
      "Создай total = 10.0 и count = 4, затем выведи total / count.",
      "Создай points = 5, прибавь 3 оператором += и выведи результат.",
      "Создай visitors = 12 и price = 2.5, затем выведи общую стоимость.",
    ],
    [
      "Если age не меньше 18, выведи Adult.",
      "Если score не меньше 50, выведи Pass, иначе выведи Fail.",
      "Проверь, равно ли secret числу 7. При совпадении выведи Correct.",
      "Разреши вход, только если age не меньше 12 И height не меньше 140.",
      "Циклом for выведи значения car от 1 до 3.",
      "Циклом for выведи i от 0 до 4, используя условие i < 5.",
      "Циклом while выведи count от 0 до 2 и увеличивай его внутри цикла.",
      "Циклом сложи числа от 1 до 5 в переменную sum и выведи сумму.",
      "В цикле от 1 до 5 пропусти число 3 с помощью continue.",
      "Создай обратный отсчёт: выведи count от 3 до 1.",
    ],
    [
      "Создай void-функцию greet, которая выводит Hi, и вызови её.",
      "Добавь функции greet параметр std::string name и выведи name.",
      "Создай doubleNumber, которая получает int и возвращает его, умноженным на 2.",
      "Создай функцию add с двумя int-параметрами, возвращающую их сумму.",
      "Создай bool-функцию isAdult, возвращающую результат age >= 18.",
      "Создай square, верни value * value и сохрани вызов square(6) в result.",
      "Сначала объяви triple, затем ниже main определи её и возвращай value * 3.",
      "Создай lengthOf с const std::string& и верни text.size().",
      "Создай addThree, которая использует уже готовую функцию add.",
      "Создай seatsLeft, возвращающую total - occupied.",
    ],
    [
      "Создай ссылку alias на value, через alias присвой 20 и выведи value.",
      "Создай increment с параметром int& и увеличь переданную переменную.",
      "Создай swapValues с двумя ссылками и поменяй значения через temp.",
      "Создай указатель ptr, сохрани в нём адрес value и выведи сам адрес.",
      "Разыменуй ptr оператором * и выведи значение 42.",
      "Через *ptr присвой value новое значение 25, затем выведи value.",
      "Перед разыменованием проверь, что ptr не равен nullptr.",
      "Передай строку в printName как const std::string& и выведи её.",
      "Через *(ptr + 1) выведи второй элемент массива numbers.",
      "Создай addPassenger(int& count), которая увеличивает число пассажиров.",
    ],
    [
      "Создай класс Greeter с публичным методом sayHi, выводящим Hi.",
      "Создай Ride с приватным speed_ = 10 и публичным const-методом speed().",
      "Добавь Ride конструктор, который присваивает параметр seats полю seats_.",
      "Перепиши конструктор Ride с использованием списка инициализации.",
      "Добавь Ride const-метод capacity(), возвращающий seats_.",
      "Создай Counter с increment(), value() и приватным value_ = 0.",
      "Добавь Ride методы setSpeed(int) и speed() для изменения и чтения скорости.",
      "Создай два объекта Ride со скоростями 10 и 30 и выведи обе скорости.",
      "Создай Rectangle с width_, height_ и методом area(), возвращающим их произведение.",
      "Собери полный класс Ride: конструктор, private seats_ и const capacity().",
    ],
  ],
  uk: [
    [
      "Виведи точний текст Hello, C++! за допомогою std::cout.",
      "Виведи текст My first program. Не забудь лапки та крапку з комою.",
      "Однією командою виведи текст Score: і число 10, використавши два оператори <<.",
      "Виведи Line 1 і Line 2 на різних рядках за допомогою \\n усередині тексту.",
      "Напиши дві окремі команди std::cout: перша виводить A, друга B.",
      "Виведи число 42 без лапок. Воно має бути числом, а не текстом.",
      "Виведи результат виразу 2 + 3. Не обчислюй його заздалегідь вручну.",
      "Поєднай текст Cars: і число 3 в одній команді std::cout.",
      "Виведи Ready та заверши рядок за допомогою std::endl.",
      "З порожнього місця склади повну програму, яка виводить I can code!.",
    ],
    [
      "Створи цілочисельну змінну age зі значенням 20 і виведи її.",
      "Створи дробову змінну price зі значенням 4.5 і виведи її.",
      "Створи логічну змінну open зі значенням true і виведи її.",
      "Створи std::string name зі значенням Alex і виведи name.",
      "Створи score зі значенням 10, потім присвой 15 і виведи нове значення.",
      "Створи константу seats зі значенням 24 і виведи її.",
      "Створи a = 7 і b = 5, потім виведи суму a + b.",
      "Створи total = 10.0 і count = 4, потім виведи total / count.",
      "Створи points = 5, додай 3 оператором += і виведи результат.",
      "Створи visitors = 12 і price = 2.5, потім виведи загальну вартість.",
    ],
    [
      "Якщо age не менше 18, виведи Adult.",
      "Якщо score не менше 50, виведи Pass, інакше виведи Fail.",
      "Перевір, чи дорівнює secret числу 7. Якщо так, виведи Correct.",
      "Дозволь вхід, лише якщо age не менше 12 І height не менше 140.",
      "Циклом for виведи значення car від 1 до 3.",
      "Циклом for виведи i від 0 до 4, використовуючи умову i < 5.",
      "Циклом while виведи count від 0 до 2 і збільшуй його всередині циклу.",
      "Циклом додай числа від 1 до 5 у sum і виведи суму.",
      "У циклі від 1 до 5 пропусти число 3 за допомогою continue.",
      "Створи зворотний відлік: виведи count від 3 до 1.",
    ],
    [
      "Створи void-функцію greet, яка виводить Hi, і виклич її.",
      "Додай функції greet параметр std::string name і виведи name.",
      "Створи doubleNumber, яка отримує int і повертає його, помноженим на 2.",
      "Створи add із двома int-параметрами, що повертає їхню суму.",
      "Створи bool-функцію isAdult, яка повертає age >= 18.",
      "Створи square, поверни value * value і збережи square(6) у result.",
      "Спочатку оголоси triple, потім нижче main визнач її та повертай value * 3.",
      "Створи lengthOf із const std::string& і поверни text.size().",
      "Створи addThree, яка використовує вже готову функцію add.",
      "Створи seatsLeft, яка повертає total - occupied.",
    ],
    [
      "Створи посилання alias на value, через alias присвой 20 і виведи value.",
      "Створи increment із параметром int& і збільш передану змінну.",
      "Створи swapValues із двома посиланнями та поміняй значення через temp.",
      "Створи вказівник ptr, збережи адресу value і виведи саму адресу.",
      "Розіменуй ptr оператором * і виведи значення 42.",
      "Через *ptr присвой value нове значення 25, потім виведи value.",
      "Перед розіменуванням перевір, що ptr не дорівнює nullptr.",
      "Передай рядок у printName як const std::string& і виведи його.",
      "Через *(ptr + 1) виведи другий елемент масиву numbers.",
      "Створи addPassenger(int& count), яка збільшує кількість пасажирів.",
    ],
    [
      "Створи клас Greeter із публічним методом sayHi, який виводить Hi.",
      "Створи Ride із приватним speed_ = 10 і публічним const-методом speed().",
      "Додай Ride конструктор, який присвоює параметр seats полю seats_.",
      "Перепиши конструктор Ride з використанням списку ініціалізації.",
      "Додай Ride const-метод capacity(), який повертає seats_.",
      "Створи Counter з increment(), value() і приватним value_ = 0.",
      "Додай Ride методи setSpeed(int) і speed() для зміни та читання швидкості.",
      "Створи два об’єкти Ride зі швидкостями 10 і 30 та виведи обидві.",
      "Створи Rectangle з width_, height_ і методом area(), що повертає їхній добуток.",
      "Склади повний клас Ride: конструктор, private seats_ і const capacity().",
    ],
  ],
  fi: [
    [
      "Tulosta täsmälleen Hello, C++! käyttäen std::cout-oliota.",
      "Tulosta My first program. Muista lainausmerkit ja puolipiste.",
      "Tulosta yhdellä lauseella teksti Score: ja luku 10 käyttäen kahta <<-operaattoria.",
      "Tulosta Line 1 ja Line 2 eri riveille käyttämällä tekstissä merkintää \\n.",
      "Kirjoita kaksi std::cout-lausetta: ensimmäinen tulostaa A ja toinen B.",
      "Tulosta luku 42 ilman lainausmerkkejä, jotta se on luku eikä tekstiä.",
      "Tulosta lausekkeen 2 + 3 tulos. Älä laske tulosta valmiiksi.",
      "Yhdistä teksti Cars: ja luku 3 samaan std::cout-lauseeseen.",
      "Tulosta Ready ja päätä rivi std::endl-operaatiolla.",
      "Rakenna tyhjästä kokonainen ohjelma, joka tulostaa I can code!.",
    ],
    [
      "Luo int-muuttuja age arvolla 20 ja tulosta se.",
      "Luo double-muuttuja price arvolla 4.5 ja tulosta se.",
      "Luo bool-muuttuja open arvolla true ja tulosta se.",
      "Luo std::string name arvolla Alex ja tulosta name.",
      "Luo score arvolla 10, sijoita siihen 15 ja tulosta uusi arvo.",
      "Luo vakio seats arvolla 24 ja tulosta se.",
      "Luo a = 7 ja b = 5, ja tulosta summa a + b.",
      "Luo total = 10.0 ja count = 4, ja tulosta total / count.",
      "Luo points = 5, lisää 3 operaattorilla += ja tulosta tulos.",
      "Luo visitors = 12 ja price = 2.5, ja tulosta kokonaishinta.",
    ],
    [
      "Jos age on vähintään 18, tulosta Adult.",
      "Jos score on vähintään 50, tulosta Pass, muuten Fail.",
      "Tarkista, onko secret yhtä suuri kuin 7. Jos on, tulosta Correct.",
      "Salli pääsy vain, kun age on vähintään 12 JA height vähintään 140.",
      "Tulosta for-silmukalla car-arvot yhdestä kolmeen.",
      "Tulosta for-silmukalla i-arvot nollasta neljään ehdolla i < 5.",
      "Tulosta while-silmukalla count nollasta kahteen ja kasvata sitä silmukassa.",
      "Laske silmukalla luvut yhdestä viiteen muuttujaan sum ja tulosta summa.",
      "Ohita silmukassa luku 3 continue-lauseella.",
      "Tee lähtölaskenta ja tulosta count kolmesta yhteen.",
    ],
    [
      "Luo void-funktio greet, joka tulostaa Hi, ja kutsu sitä.",
      "Lisää greet-funktiolle std::string name -parametri ja tulosta name.",
      "Luo doubleNumber, joka saa int-arvon ja palauttaa sen kerrottuna kahdella.",
      "Luo add kahdella int-parametrilla ja palauta niiden summa.",
      "Luo bool-funktio isAdult, joka palauttaa lausekkeen age >= 18.",
      "Luo square, palauta value * value ja tallenna square(6) muuttujaan result.",
      "Esittele ensin triple ja määrittele se main-funktion jälkeen palauttamaan value * 3.",
      "Luo lengthOf parametrilla const std::string& ja palauta text.size().",
      "Luo addThree, joka käyttää valmista add-funktiota.",
      "Luo seatsLeft, joka palauttaa total - occupied.",
    ],
    [
      "Luo viite alias muuttujaan value, sijoita alias-arvoksi 20 ja tulosta value.",
      "Luo increment parametrilla int& ja kasvata sille annettua muuttujaa.",
      "Luo swapValues kahdella viitteellä ja vaihda arvot temp-muuttujan avulla.",
      "Luo osoitin ptr, tallenna siihen value-muuttujan osoite ja tulosta osoite.",
      "Dereferoi ptr operaattorilla * ja tulosta arvo 42.",
      "Sijoita *ptr:n kautta value-arvoksi 25 ja tulosta value.",
      "Tarkista ennen dereferointia, ettei ptr ole nullptr.",
      "Välitä merkkijono printName-funktiolle muodossa const std::string&.",
      "Tulosta taulukon numbers toinen alkio lausekkeella *(ptr + 1).",
      "Luo addPassenger(int& count), joka kasvattaa matkustajien määrää.",
    ],
    [
      "Luo Greeter-luokka, jonka julkinen sayHi-metodi tulostaa Hi.",
      "Luo Ride, jossa on private speed_ = 10 ja public const-metodi speed().",
      "Lisää Ride-konstruktori, joka sijoittaa seats-parametrin seats_-kenttään.",
      "Kirjoita Ride-konstruktori uudelleen käyttäen alustuslistaa.",
      "Lisää Ride-luokkaan const-metodi capacity(), joka palauttaa seats_.",
      "Luo Counter, jossa ovat increment(), value() ja private value_ = 0.",
      "Lisää Ride-luokkaan setSpeed(int) ja speed() nopeuden muuttamiseen ja lukemiseen.",
      "Luo kaksi Ride-oliota nopeuksilla 10 ja 30 ja tulosta molemmat nopeudet.",
      "Luo Rectangle, jossa ovat width_, height_ ja niiden tulon palauttava area().",
      "Rakenna täydellinen Ride-luokka: konstruktori, private seats_ ja const capacity().",
    ],
  ],
  en: [
    [
      "Print the exact text Hello, C++! using std::cout.",
      "Print My first program. Remember the quotes and semicolon.",
      "In one statement, print Score: and then the number 10 using two << operators.",
      "Print Line 1 and Line 2 on separate lines using \\n inside the text.",
      "Write two separate std::cout statements: the first prints A, the second B.",
      "Print the number 42 without quotes so it is a number, not text.",
      "Print the result of 2 + 3. Let C++ perform the calculation.",
      "Combine the text Cars: and the number 3 in one std::cout statement.",
      "Print Ready and end the line with std::endl.",
      "From a blank file, build a complete program that prints I can code!.",
    ],
    [
      "Create an int variable age with value 20 and print it.",
      "Create a double variable price with value 4.5 and print it.",
      "Create a bool variable open with value true and print it.",
      "Create std::string name with value Alex and print name.",
      "Create score with value 10, assign 15 to it, then print the new value.",
      "Create a constant seats with value 24 and print it.",
      "Create a = 7 and b = 5, then print a + b.",
      "Create total = 10.0 and count = 4, then print total / count.",
      "Create points = 5, add 3 with +=, then print the result.",
      "Create visitors = 12 and price = 2.5, then print the total cost.",
    ],
    [
      "If age is at least 18, print Adult.",
      "If score is at least 50, print Pass; otherwise print Fail.",
      "Check whether secret equals 7. If it does, print Correct.",
      "Allow entry only when age is at least 12 AND height is at least 140.",
      "Use a for loop to print car values from 1 through 3.",
      "Use a for loop to print i from 0 through 4 with the condition i < 5.",
      "Use a while loop to print count from 0 through 2 and increase it inside the loop.",
      "Use a loop to add numbers 1 through 5 into sum, then print sum.",
      "In a loop from 1 through 5, skip the number 3 with continue.",
      "Create a countdown that prints count from 3 down to 1.",
    ],
    [
      "Create a void function greet that prints Hi, then call it.",
      "Give greet a std::string name parameter and print name.",
      "Create doubleNumber that receives an int and returns it multiplied by 2.",
      "Create add with two int parameters and return their sum.",
      "Create a bool function isAdult that returns age >= 18.",
      "Create square, return value * value, and store square(6) in result.",
      "Declare triple first, then define it below main to return value * 3.",
      "Create lengthOf with const std::string& and return text.size().",
      "Create addThree that reuses the existing add function.",
      "Create seatsLeft that returns total - occupied.",
    ],
    [
      "Create reference alias for value, assign 20 through alias, then print value.",
      "Create increment with an int& parameter and increase the supplied variable.",
      "Create swapValues with two references and swap the values through temp.",
      "Create pointer ptr, store the address of value, and print the address itself.",
      "Dereference ptr with * and print the value 42.",
      "Assign 25 through *ptr, then print value.",
      "Before dereferencing, check that ptr is not nullptr.",
      "Pass a string to printName as const std::string& and print it.",
      "Print the second item of numbers through *(ptr + 1).",
      "Create addPassenger(int& count) that increases the passenger count.",
    ],
    [
      "Create class Greeter with a public sayHi method that prints Hi.",
      "Create Ride with private speed_ = 10 and a public const speed() method.",
      "Add a Ride constructor that assigns the seats parameter to seats_.",
      "Rewrite the Ride constructor using an initializer list.",
      "Add a const capacity() method to Ride that returns seats_.",
      "Create Counter with increment(), value(), and private value_ = 0.",
      "Add setSpeed(int) and speed() to Ride to change and read its speed.",
      "Create two Ride objects with speeds 10 and 30 and print both speeds.",
      "Create Rectangle with width_, height_, and area() returning their product.",
      "Build the complete Ride class: constructor, private seats_, and const capacity().",
    ],
  ],
  th: [
    [
      "แสดงข้อความ Hello, C++! ให้ตรงทุกตัวอักษรด้วย std::cout",
      "แสดงข้อความ My first program อย่าลืมอัญประกาศคู่และเครื่องหมายอัฒภาค",
      "ใช้คำสั่งเดียวแสดงข้อความ Score: แล้วตามด้วยตัวเลข 10 โดยใช้ตัวดำเนินการ << สองครั้ง",
      "แสดง Line 1 และ Line 2 คนละบรรทัด โดยใช้ \\n ภายในข้อความ",
      "เขียนคำสั่ง std::cout แยกกันสองคำสั่ง คำสั่งแรกแสดง A และคำสั่งที่สองแสดง B",
      "แสดงตัวเลข 42 โดยไม่ใส่อัญประกาศ เพื่อให้เป็นตัวเลขไม่ใช่ข้อความ",
      "แสดงผลลัพธ์ของ 2 + 3 โดยให้ C++ เป็นผู้คำนวณ",
      "รวมข้อความ Cars: และตัวเลข 3 ไว้ในคำสั่ง std::cout เดียว",
      "แสดง Ready แล้วจบบรรทัดด้วย std::endl",
      "เริ่มจากไฟล์ว่าง แล้วสร้างโปรแกรมสมบูรณ์ที่แสดง I can code!",
    ],
    [
      "สร้างตัวแปร int ชื่อ age ค่า 20 แล้วแสดงค่า",
      "สร้างตัวแปร double ชื่อ price ค่า 4.5 แล้วแสดงค่า",
      "สร้างตัวแปร bool ชื่อ open ค่า true แล้วแสดงค่า",
      "สร้าง std::string ชื่อ name ที่มีค่า Alex แล้วแสดง name",
      "สร้าง score ค่า 10 จากนั้นกำหนดค่าใหม่เป็น 15 แล้วแสดงค่าใหม่",
      "สร้างค่าคงที่ seats ค่า 24 แล้วแสดงค่า",
      "สร้าง a = 7 และ b = 5 แล้วแสดง a + b",
      "สร้าง total = 10.0 และ count = 4 แล้วแสดง total / count",
      "สร้าง points = 5 เพิ่มค่า 3 ด้วย += แล้วแสดงผลลัพธ์",
      "สร้าง visitors = 12 และ price = 2.5 แล้วแสดงราคารวม",
    ],
    [
      "ถ้า age มีค่าอย่างน้อย 18 ให้แสดง Adult",
      "ถ้า score มีค่าอย่างน้อย 50 ให้แสดง Pass มิฉะนั้นให้แสดง Fail",
      "ตรวจว่า secret เท่ากับ 7 หรือไม่ ถ้าเท่ากันให้แสดง Correct",
      "อนุญาตให้เข้าได้เมื่อ age อย่างน้อย 12 และ height อย่างน้อย 140 เท่านั้น",
      "ใช้ลูป for แสดงค่า car ตั้งแต่ 1 ถึง 3",
      "ใช้ลูป for แสดง i ตั้งแต่ 0 ถึง 4 ด้วยเงื่อนไข i < 5",
      "ใช้ลูป while แสดง count ตั้งแต่ 0 ถึง 2 และเพิ่มค่าภายในลูป",
      "ใช้ลูปรวมตัวเลข 1 ถึง 5 ไว้ใน sum แล้วแสดง sum",
      "ในลูปตั้งแต่ 1 ถึง 5 ให้ข้ามเลข 3 ด้วย continue",
      "สร้างการนับถอยหลังที่แสดง count จาก 3 ลงไปถึง 1",
    ],
    [
      "สร้างฟังก์ชัน void ชื่อ greet ที่แสดง Hi แล้วเรียกใช้ฟังก์ชัน",
      "เพิ่มพารามิเตอร์ std::string name ให้ greet แล้วแสดง name",
      "สร้าง doubleNumber ที่รับ int และคืนค่าที่คูณด้วย 2",
      "สร้าง add ที่มีพารามิเตอร์ int สองตัวและคืนผลบวก",
      "สร้างฟังก์ชัน bool ชื่อ isAdult ที่คืนค่า age >= 18",
      "สร้าง square ให้คืน value * value แล้วเก็บ square(6) ไว้ใน result",
      "ประกาศ triple ก่อน แล้วนิยามไว้ใต้ main ให้คืนค่า value * 3",
      "สร้าง lengthOf ที่รับ const std::string& และคืน text.size()",
      "สร้าง addThree โดยนำฟังก์ชัน add ที่มีอยู่กลับมาใช้",
      "สร้าง seatsLeft ที่คืนค่า total - occupied",
    ],
    [
      "สร้าง reference ชื่อ alias สำหรับ value กำหนดค่า 20 ผ่าน alias แล้วแสดง value",
      "สร้าง increment ที่รับพารามิเตอร์ int& แล้วเพิ่มค่าตัวแปรที่ส่งเข้ามา",
      "สร้าง swapValues ที่รับ reference สองตัว และสลับค่าด้วย temp",
      "สร้าง pointer ชื่อ ptr เก็บที่อยู่ของ value แล้วแสดงตัวที่อยู่นั้น",
      "dereference ptr ด้วย * แล้วแสดงค่า 42",
      "กำหนดค่า 25 ผ่าน *ptr แล้วแสดง value",
      "ก่อน dereference ให้ตรวจว่า ptr ไม่ใช่ nullptr",
      "ส่งสตริงไปยัง printName แบบ const std::string& แล้วแสดงผล",
      "แสดงสมาชิกตัวที่สองของ numbers ผ่าน *(ptr + 1)",
      "สร้าง addPassenger(int& count) ที่เพิ่มจำนวนผู้โดยสาร",
    ],
    [
      "สร้างคลาส Greeter ที่มีเมธอด public ชื่อ sayHi สำหรับแสดง Hi",
      "สร้าง Ride ที่มี private speed_ = 10 และเมธอด public แบบ const ชื่อ speed()",
      "เพิ่ม constructor ของ Ride ที่กำหนดพารามิเตอร์ seats ให้กับ seats_",
      "เขียน constructor ของ Ride ใหม่โดยใช้ initializer list",
      "เพิ่มเมธอด const ชื่อ capacity() ใน Ride ให้คืนค่า seats_",
      "สร้าง Counter ที่มี increment(), value() และ private value_ = 0",
      "เพิ่ม setSpeed(int) และ speed() ใน Ride เพื่อเปลี่ยนและอ่านความเร็ว",
      "สร้างออบเจ็กต์ Ride สองตัวที่มีความเร็ว 10 และ 30 แล้วแสดงความเร็วทั้งสอง",
      "สร้าง Rectangle ที่มี width_, height_ และ area() ซึ่งคืนผลคูณของทั้งสองค่า",
      "สร้างคลาส Ride ให้สมบูรณ์ โดยมี constructor, private seats_ และ const capacity()",
    ],
  ],
};
