import type { Language } from "./content";

export const taskExplanations: Record<Language, string[][]> = {
  ru: [
    [
      "`std::cout` отправляет данные в консоль. Оператор `<<` передаёт ему значение справа, двойные кавычки обозначают текст, а `;` завершает команду.",
      "В кавычках нужно написать текст точно так, как он должен появиться на экране. Регистр букв и пробелы внутри строки являются частью результата.",
      "`Score: ` является текстом, поэтому его пишут в двойных кавычках. `10` является числовым литералом и пишется без кавычек. Запись `\"10\"` создала бы текст, с которым нельзя выполнять обычные числовые вычисления. Второй `<<` добавляет число в тот же вывод.",
      "Последовательность `\\n` внутри текста называется управляющей последовательностью. Она не выводит символы `\\` и `n`, а переводит курсор на новую строку.",
      "Каждая команда `std::cout` является отдельной инструкцией и заканчивается своим `;`. C++ не добавляет пробел или новую строку между двумя командами автоматически.",
      "Запись `42` без кавычек создаёт число. Запись `\"42\"` создаёт два текстовых символа, поэтому для числового значения кавычки не нужны.",
      "Выражение `2 + 3` вычисляется до вывода, поэтому `std::cout` получает готовое число `5`. Если взять выражение в кавычки, программа напечатает сами символы `2 + 3`.",
      "Текст и число можно отправлять в один поток по очереди. Текст берут в кавычки, число пишут без них, а перед каждым следующим элементом ставят ещё один `<<`.",
      "`std::endl` является специальным элементом потока, а не текстом, поэтому кавычки ему не нужны. Он начинает новую строку и сразу отправляет накопленный вывод в консоль.",
      "Полная программа требует `#include <iostream>` для `std::cout`, функции `int main()`, фигурных скобок и `return 0;`. Код выполнения располагается внутри `main`.",
    ],
    [
      "`int age = 20;` одновременно создаёт целочисленную переменную, даёт ей имя и начальное значение. При выводе имени `age` кавычки не ставят, иначе напечатается слово, а не содержимое переменной.",
      "Тип `double` хранит дробные числа. В коде десятичную часть отделяют точкой, поэтому пишут `4.5`, а не `4,5`.",
      "Тип `bool` хранит только `true` или `false`. Эти слова являются значениями C++ и пишутся без кавычек и строчными буквами.",
      "`std::string` хранит текст, поэтому начальное значение `\"Alex\"` находится в кавычках. Для типа нужен `#include <string>`, а имя переменной при выводе пишется без кавычек.",
      "Тип указывают только при создании переменной. Позже команда `score = 15;` заменяет старое значение, а повторное `int score` попыталось бы создать новую переменную.",
      "Ключевое слово `const` запрещает менять переменную после создания. Оно подходит для значений, которые должны оставаться неизменными, например количества мест.",
      "В выражении `a + b` используются значения переменных. Сначала C++ выполняет сложение, затем `std::cout` выводит полученный результат.",
      "Если хотя бы один операнд деления имеет тип `double`, результат сохраняет дробную часть. Поэтому `10.0 / 4` даёт `2.5`, а деление двух `int` отбросило бы дробную часть.",
      "Оператор `+=` складывает текущее значение с правой частью и сохраняет результат обратно. `points += 3;` означает то же, что `points = points + 3;`.",
      "Оператор `*` умножает значения. При умножении `int` на `double` C++ преобразует результат к дробному типу, чтобы не потерять десятичную часть.",
    ],
    [
      "`if` выполняет блок в фигурных скобках только при истинном условии. `>=` означает «больше или равно», а само условие обязательно помещают в круглые скобки.",
      "Блок `else` выполняется только тогда, когда условие `if` ложно. Поэтому программа выбирает ровно один из двух путей.",
      "Оператор `==` сравнивает два значения. Один знак `=` не сравнивает, а присваивает новое значение, поэтому в условии равенства нужны два знака.",
      "Оператор `&&` означает логическое И. Весь результат станет `true` только тогда, когда истинны и условие возраста, и условие роста.",
      "В круглых скобках `for` находятся три части: начальное значение, условие продолжения и изменение счётчика. Точки с запятой разделяют эти части.",
      "Счётчик начинается с `0` и повторяется, пока `i < 5`. Поэтому цикл использует значения `0, 1, 2, 3, 4`, но не `5`.",
      "`while` проверяет условие перед каждым повтором. Счётчик нужно увеличивать внутри цикла, иначе условие останется истинным и цикл станет бесконечным.",
      "Переменная `sum` является накопителем. Команда `sum += i;` на каждом повторе добавляет очередное число к уже собранной сумме.",
      "`continue` немедленно пропускает оставшуюся часть текущего повтора. Цикл не завершается, а переходит к следующему значению счётчика.",
      "Оператор `--count` уменьшает значение на единицу. Условие `count >= 1` удерживает в цикле значения `3, 2, 1` и останавливает его перед нулём.",
    ],
    [
      "Тип `void` означает, что функция выполняет действие, но не возвращает значение. Скобки `()` обозначают отсутствие параметров, а вызов `greet();` запускает функцию.",
      "Параметр `std::string name` получает текст внутри функции. При вызове `\"Alex\"` находится в кавычках как текстовый литерал, а внутри функции `name` пишется без кавычек как переменная.",
      "Тип `int` перед именем функции обещает целочисленный результат. `return number * 2;` вычисляет значение и передаёт его обратно в место вызова.",
      "Параметры перечисляют через запятую, и у каждого указывают свой тип. При вызове аргументы передаются в том же порядке: первое значение попадает в `a`, второе в `b`.",
      "Функция типа `bool` должна вернуть `true` или `false`. Сравнение `age >= 18` уже создаёт такое логическое значение, поэтому его можно вернуть напрямую.",
      "Результат функции можно сохранить в переменной. Сначала выполняется `square(6)`, затем возвращённое число записывается в `result`.",
      "Объявление `int triple(int value);` заранее сообщает компилятору имя, параметры и тип результата. Полное определение ниже содержит тело функции и объясняет, как получить результат.",
      "`const std::string&` передаёт строку без копирования и запрещает функции менять её. Метод `.size()` возвращает количество символов строки.",
      "Вложенные вызовы вычисляются изнутри наружу. Сначала `add(a, b)` возвращает промежуточную сумму, затем внешний `add` прибавляет `c`.",
      "Имена параметров объясняют смысл данных. Функция получает `total` и `occupied`, а `return total - occupied;` возвращает количество свободных мест.",
    ],
    [
      "Запись `int& alias = value;` создаёт ссылку, то есть второе имя той же переменной. Поэтому изменение `alias` сразу изменяет `value`.",
      "Параметр `int& value` принимает не копию, а исходную переменную. Оператор `++value` увеличивает именно значение, переданное из `main`.",
      "Для обмена нужен временный `temp`, иначе первое присваивание уничтожит одно из исходных значений. Ссылки позволяют функции менять обе внешние переменные.",
      "`int* ptr` объявляет указатель, а `&value` получает адрес переменной. Вывод `ptr` показывает адрес, а не число, которое хранится по этому адресу.",
      "Звёздочка перед готовым указателем означает разыменование. Выражение `*ptr` обращается к значению, которое находится по сохранённому адресу.",
      "Разыменованный указатель можно использовать слева от `=`. Команда `*ptr = 25;` записывает новое значение прямо в связанную переменную `value`.",
      "`nullptr` означает, что указатель ни на что не указывает. Разыменовывать его опасно, поэтому сначала проверяют условие `ptr != nullptr`.",
      "`const std::string&` сочетает экономную передачу без копии и защиту от изменения. Функция может читать и выводить строку, но не должна её менять.",
      "Имя массива указывает на его первый элемент. `ptr + 1` сдвигает адрес на второй элемент, а внешняя `*` получает значение по новому адресу.",
      "Имя аргумента и имя параметра могут отличаться. `passengers` из `main` становится ссылкой `count` внутри функции, но обе записи обращаются к одному значению.",
    ],
    [
      "`class Greeter` создаёт новый тип. `public:` открывает метод для вызова снаружи, `g.sayHi()` вызывает его через точку, а после закрывающей скобки класса нужен `;`.",
      "Поле после `private:` нельзя читать напрямую из `main`. Публичный метод `speed() const` безопасно возвращает значение, а `const` обещает не изменять объект.",
      "Конструктор имеет то же имя, что класс, и не указывает возвращаемый тип. Он запускается автоматически при создании `Ride ride(24)` и записывает параметр в поле.",
      "Список инициализации находится после двоеточия перед телом конструктора. Запись `seats_(seats)` создаёт поле сразу с нужным значением и предпочтительнее последующего присваивания.",
      "Метод `capacity() const` является геттером: он читает закрытое поле и возвращает его наружу. `const` показывает, что чтение не изменяет объект.",
      "Объект хранит состояние в поле `value_`. Метод `increment()` меняет его, а `value() const` только читает, поэтому данные и действия объединены внутри класса.",
      "Сеттер `setSpeed(int)` изменяет закрытое поле, а геттер `speed() const` читает его. Так класс контролирует доступ к своему состоянию.",
      "Каждый объект класса имеет собственные поля. Поэтому `slow(10)` и `fast(30)` хранят разные скорости, хотя созданы из одного типа `Ride`.",
      "Конструктор может инициализировать несколько полей через запятую. Метод `area()` использует значения `width_` и `height_` текущего объекта.",
      "В полном классе важен порядок частей: открытый конструктор и метод, затем закрытое поле. Определение класса завершается `};`, а объект использует интерфейс через точку.",
    ],
  ],
  uk: [
    [
      "`std::cout` надсилає дані до консолі. Оператор `<<` передає йому значення праворуч, подвійні лапки позначають текст, а `;` завершує команду.",
      "У лапках потрібно написати текст саме так, як він має з’явитися на екрані. Регістр літер і пробіли всередині рядка є частиною результату.",
      "`Score: ` є текстом, тому його пишуть у подвійних лапках. `10` є числовим літералом і пишеться без лапок. Запис `\"10\"` створив би текст, з яким не можна виконувати звичайні числові обчислення. Другий `<<` додає число до того самого виведення.",
      "Послідовність `\\n` усередині тексту називається керувальною послідовністю. Вона не виводить символи `\\` і `n`, а переводить курсор на новий рядок.",
      "Кожна команда `std::cout` є окремою інструкцією і завершується власною `;`. C++ не додає пробіл або новий рядок між командами автоматично.",
      "Запис `42` без лапок створює число. Запис `\"42\"` створює два текстові символи, тому для числового значення лапки не потрібні.",
      "Вираз `2 + 3` обчислюється до виведення, тому `std::cout` отримує готове число `5`. У лапках програма надрукувала б самі символи `2 + 3`.",
      "Текст і число можна надсилати в один потік по черзі. Текст беруть у лапки, число пишуть без них, а перед кожним наступним елементом ставлять ще один `<<`.",
      "`std::endl` є спеціальним елементом потоку, а не текстом, тому лапки йому не потрібні. Він починає новий рядок і одразу надсилає накопичене виведення до консолі.",
      "Повна програма потребує `#include <iostream>` для `std::cout`, функції `int main()`, фігурних дужок і `return 0;`. Код виконання розташовують усередині `main`.",
    ],
    [
      "`int age = 20;` одночасно створює цілочисельну змінну, дає їй ім’я та початкове значення. Під час виведення `age` лапки не ставлять, інакше надрукується слово, а не значення.",
      "Тип `double` зберігає дробові числа. У коді десяткову частину відокремлюють крапкою, тому пишуть `4.5`, а не `4,5`.",
      "Тип `bool` зберігає лише `true` або `false`. Ці слова є значеннями C++ і пишуться без лапок та малими літерами.",
      "`std::string` зберігає текст, тому початкове значення `\"Alex\"` міститься в лапках. Для типу потрібен `#include <string>`, а ім’я змінної виводять без лапок.",
      "Тип указують лише під час створення змінної. Пізніше `score = 15;` замінює старе значення, а повторне `int score` намагалося б створити нову змінну.",
      "Ключове слово `const` забороняє змінювати змінну після створення. Воно підходить для значень, які мають залишатися незмінними.",
      "У виразі `a + b` використовуються значення змінних. Спочатку C++ виконує додавання, потім `std::cout` виводить результат.",
      "Якщо хоча б один операнд ділення має тип `double`, результат зберігає дробову частину. Тому `10.0 / 4` дає `2.5`, а ділення двох `int` відкинуло б її.",
      "Оператор `+=` додає праву частину до поточного значення і зберігає результат назад. `points += 3;` означає те саме, що `points = points + 3;`.",
      "Оператор `*` множить значення. Під час множення `int` на `double` C++ перетворює результат на дробовий тип, щоб не втратити десяткову частину.",
    ],
    [
      "`if` виконує блок у фігурних дужках лише за істинної умови. `>=` означає «більше або дорівнює», а умову обов’язково беруть у круглі дужки.",
      "Блок `else` виконується лише тоді, коли умова `if` хибна. Отже, програма обирає рівно один із двох шляхів.",
      "Оператор `==` порівнює два значення. Один знак `=` не порівнює, а присвоює нове значення, тому для рівності потрібні два знаки.",
      "Оператор `&&` означає логічне І. Увесь результат стане `true` лише тоді, коли істинні й умова віку, й умова зросту.",
      "У круглих дужках `for` є три частини: початкове значення, умова продовження та зміна лічильника. Крапки з комою розділяють ці частини.",
      "Лічильник починається з `0` і повторюється, поки `i < 5`. Тому цикл використовує `0, 1, 2, 3, 4`, але не `5`.",
      "`while` перевіряє умову перед кожним повтором. Лічильник потрібно збільшувати всередині циклу, інакше умова залишиться істинною назавжди.",
      "Змінна `sum` є накопичувачем. Команда `sum += i;` на кожному повторі додає наступне число до вже зібраної суми.",
      "`continue` негайно пропускає решту поточного повтору. Цикл не завершується, а переходить до наступного значення лічильника.",
      "Оператор `--count` зменшує значення на одиницю. Умова `count >= 1` залишає в циклі `3, 2, 1` і зупиняє його перед нулем.",
    ],
    [
      "Тип `void` означає, що функція виконує дію, але не повертає значення. Дужки `()` позначають відсутність параметрів, а `greet();` запускає функцію.",
      "Параметр `std::string name` отримує текст усередині функції. Під час виклику `\"Alex\"` пишуть у лапках як текст, а `name` усередині функції є змінною без лапок.",
      "Тип `int` перед ім’ям функції обіцяє цілочисельний результат. `return number * 2;` обчислює значення і передає його назад до місця виклику.",
      "Параметри перелічують через кому, і кожен має власний тип. Під час виклику аргументи передаються в тому самому порядку.",
      "Функція типу `bool` має повернути `true` або `false`. Порівняння `age >= 18` уже створює логічне значення, тому його можна повернути безпосередньо.",
      "Результат функції можна зберегти у змінній. Спочатку виконується `square(6)`, потім повернене число записується в `result`.",
      "Оголошення `int triple(int value);` заздалегідь повідомляє компілятору ім’я, параметри й тип результату. Повне визначення нижче містить тіло функції.",
      "`const std::string&` передає рядок без копіювання і забороняє функції змінювати його. Метод `.size()` повертає кількість символів.",
      "Вкладені виклики обчислюються зсередини назовні. Спочатку `add(a, b)` повертає проміжну суму, потім зовнішній `add` додає `c`.",
      "Імена параметрів пояснюють значення даних. Функція отримує `total` і `occupied`, а `return total - occupied;` повертає кількість вільних місць.",
    ],
    [
      "Запис `int& alias = value;` створює посилання, тобто друге ім’я тієї самої змінної. Тому зміна `alias` одразу змінює `value`.",
      "Параметр `int& value` приймає не копію, а початкову змінну. Оператор `++value` збільшує саме значення, передане з `main`.",
      "Для обміну потрібен тимчасовий `temp`, інакше перше присвоєння знищить одне з початкових значень. Посилання дозволяють змінити обидві зовнішні змінні.",
      "`int* ptr` оголошує вказівник, а `&value` отримує адресу змінної. Виведення `ptr` показує адресу, а не число за цією адресою.",
      "Зірочка перед готовим вказівником означає розіменування. Вираз `*ptr` звертається до значення, що лежить за збереженою адресою.",
      "Розіменований вказівник можна поставити ліворуч від `=`. Команда `*ptr = 25;` записує нове значення безпосередньо у пов’язану змінну `value`.",
      "`nullptr` означає, що вказівник ні на що не вказує. Розіменовувати його небезпечно, тому спочатку перевіряють `ptr != nullptr`.",
      "`const std::string&` поєднує передачу без копії та захист від зміни. Функція може читати й виводити рядок, але не змінювати його.",
      "Ім’я масиву вказує на перший елемент. `ptr + 1` пересуває адресу до другого елемента, а зовнішня `*` отримує значення за новою адресою.",
      "Ім’я аргументу та параметра можуть відрізнятися. `passengers` із `main` стає посиланням `count` усередині функції, але це те саме значення.",
    ],
    [
      "`class Greeter` створює новий тип. `public:` відкриває метод для зовнішнього виклику, `g.sayHi()` викликає його через крапку, а після класу потрібна `;`.",
      "Поле після `private:` не можна читати безпосередньо з `main`. Публічний метод `speed() const` безпечно повертає значення й обіцяє не змінювати об’єкт.",
      "Конструктор має те саме ім’я, що й клас, і не має типу результату. Він запускається автоматично під час створення `Ride ride(24)` і записує параметр у поле.",
      "Список ініціалізації розташований після двокрапки перед тілом конструктора. `seats_(seats)` одразу створює поле з потрібним значенням.",
      "Метод `capacity() const` є геттером: він читає закрите поле та повертає його назовні. `const` показує, що читання не змінює об’єкт.",
      "Об’єкт зберігає стан у полі `value_`. Метод `increment()` змінює його, а `value() const` лише читає, тому дані й дії поєднані в класі.",
      "Сеттер `setSpeed(int)` змінює закрите поле, а геттер `speed() const` читає його. Так клас контролює доступ до свого стану.",
      "Кожен об’єкт класу має власні поля. Тому `slow(10)` і `fast(30)` зберігають різні швидкості, хоча створені з одного типу `Ride`.",
      "Конструктор може ініціалізувати кілька полів через кому. Метод `area()` використовує `width_` і `height_` поточного об’єкта.",
      "У повному класі важливий порядок: відкритий конструктор і метод, потім закрите поле. Визначення класу завершується `};`, а об’єкт працює через публічний інтерфейс.",
    ],
  ],
  fi: [
    [
      "`std::cout` lähettää tietoa konsoliin. Operaattori `<<` siirtää oikealla olevan arvon tulosteeseen, lainausmerkit merkitsevät tekstiä ja `;` päättää lauseen.",
      "Kirjoita lainausmerkkien sisään teksti täsmälleen siinä muodossa kuin sen pitää näkyä. Kirjainkoko ja välilyönnit ovat osa tulosta.",
      "`Score: ` on tekstiä, joten se kirjoitetaan lainausmerkkeihin. `10` on lukuliteraali ja kirjoitetaan ilman lainausmerkkejä. Muoto `\"10\"` olisi tekstiä, jolla ei voi tehdä tavallisia laskutoimituksia. Toinen `<<` lisää luvun samaan tulosteeseen.",
      "Tekstin sisällä oleva `\\n` on ohjausmerkki. Se ei tulosta merkkejä `\\` ja `n`, vaan siirtää tulostuksen seuraavalle riville.",
      "Jokainen `std::cout` on oma lauseensa ja tarvitsee oman `;`-merkin. C++ ei lisää komentojen väliin automaattisesti välilyöntiä tai rivinvaihtoa.",
      "`42` ilman lainausmerkkejä on luku. `\"42\"` olisi kaksi tekstimerkkiä, joten numeerisen arvon ympärille ei laiteta lainausmerkkejä.",
      "Lauseke `2 + 3` lasketaan ennen tulostusta, joten `std::cout` saa arvon `5`. Lainausmerkeissä ohjelma tulostaisi merkit `2 + 3`.",
      "Tekstiä ja lukuja voi lähettää samaan virtaan peräkkäin. Teksti tulee lainausmerkkeihin, luku ilman niitä ja jokaisen uuden osan eteen tulee `<<`.",
      "`std::endl` on virran erikoisosa, ei tekstiä, joten se ei tarvitse lainausmerkkejä. Se aloittaa uuden rivin ja lähettää kertyneen tulosteen heti konsoliin.",
      "Täysi ohjelma tarvitsee `#include <iostream>`-rivin `std::cout`-käyttöön, `int main()`-funktion, aaltosulkeet ja `return 0;`-lauseen. Suoritettava koodi tulee `main`-funktion sisään.",
    ],
    [
      "`int age = 20;` luo kokonaislukumuuttujan, nimeää sen ja antaa alkuarvon. Tulostettaessa `age` kirjoitetaan ilman lainausmerkkejä, jotta tulostuu arvo eikä sana.",
      "Tyyppi `double` tallentaa desimaalilukuja. Desimaaliosa erotetaan koodissa pisteellä, joten kirjoitetaan `4.5`, ei `4,5`.",
      "Tyyppi `bool` tallentaa vain arvon `true` tai `false`. Ne ovat C++-arvoja ja kirjoitetaan pienillä kirjaimilla ilman lainausmerkkejä.",
      "`std::string` tallentaa tekstiä, joten alkuarvo `\"Alex\"` on lainausmerkeissä. Tyyppi tarvitsee `#include <string>`-rivin, mutta muuttujan nimi tulostetaan ilman lainausmerkkejä.",
      "Tyyppi annetaan vain muuttujaa luotaessa. Myöhemmin `score = 15;` korvaa vanhan arvon, kun taas uusi `int score` yrittäisi luoda toisen muuttujan.",
      "Avainsana `const` estää muuttujan muuttamisen luonnin jälkeen. Se sopii arvoille, joiden pitää pysyä samoina.",
      "Lauseke `a + b` käyttää muuttujien arvoja. C++ laskee summan ensin, ja `std::cout` tulostaa valmiin tuloksen.",
      "Jos ainakin toinen jakolaskun operandi on `double`, tulos säilyttää desimaaliosan. Siksi `10.0 / 4` antaa `2.5`, kun taas kahden `int`-arvon jako hukkaisi murto-osan.",
      "Operaattori `+=` lisää oikean puolen nykyiseen arvoon ja tallentaa tuloksen takaisin. `points += 3;` tarkoittaa samaa kuin `points = points + 3;`.",
      "Operaattori `*` kertoo arvot. Kun `int` kerrotaan `double`-arvolla, C++ muuntaa tuloksen desimaaliluvuksi, jotta desimaaliosa säilyy.",
    ],
    [
      "`if` suorittaa aaltosulkeissa olevan lohkon vain ehdon ollessa tosi. `>=` tarkoittaa suurempi tai yhtä suuri, ja ehto kirjoitetaan kaarisulkeisiin.",
      "`else`-lohko suoritetaan vain, kun `if`-ehto on epätosi. Ohjelma valitsee siis täsmälleen yhden kahdesta reitistä.",
      "Operaattori `==` vertaa kahta arvoa. Yksi `=` ei vertaa vaan sijoittaa uuden arvon, joten yhtäsuuruusehto tarvitsee kaksi merkkiä.",
      "Operaattori `&&` tarkoittaa loogista JA:ta. Koko ehto on `true` vain, jos sekä ikä- että pituusehto ovat tosia.",
      "`for`-silmukan kaarisulkeissa on kolme osaa: alkuarvo, jatkamisehto ja laskurin muutos. Puolipisteet erottavat osat.",
      "Laskuri alkaa arvosta `0` ja jatkaa niin kauan kuin `i < 5`. Siksi silmukka käyttää arvoja `0, 1, 2, 3, 4`, mutta ei arvoa `5`.",
      "`while` tarkistaa ehdon ennen jokaista kierrosta. Laskuria täytyy kasvattaa silmukan sisällä, muuten ehto pysyy ikuisesti totena.",
      "Muuttuja `sum` toimii kertymänä. Lause `sum += i;` lisää jokaisella kierroksella seuraavan luvun jo koottuun summaan.",
      "`continue` ohittaa heti nykyisen kierroksen loppuosan. Silmukka ei pääty, vaan jatkaa seuraavalla laskurin arvolla.",
      "Operaattori `--count` pienentää arvoa yhdellä. Ehto `count >= 1` pitää arvot `3, 2, 1` mukana ja pysäyttää silmukan ennen nollaa.",
    ],
    [
      "Tyyppi `void` tarkoittaa, että funktio tekee toiminnon mutta ei palauta arvoa. Sulkeet `()` kertovat, ettei parametreja ole, ja `greet();` kutsuu funktiota.",
      "Parametri `std::string name` vastaanottaa tekstin funktioon. Kutsussa `\"Alex\"` on tekstiliteraali lainausmerkeissä, mutta funktion sisällä `name` on muuttuja ilman lainausmerkkejä.",
      "Funktion nimen edessä oleva `int` lupaa kokonaislukutuloksen. `return number * 2;` laskee arvon ja palauttaa sen kutsukohtaan.",
      "Parametrit erotetaan pilkuilla, ja jokaisella on oma tyyppi. Kutsussa argumentit annetaan samassa järjestyksessä: ensimmäinen menee muuttujaan `a`, toinen muuttujaan `b`.",
      "`bool`-funktion pitää palauttaa `true` tai `false`. Vertailu `age >= 18` tuottaa jo tällaisen totuusarvon, joten sen voi palauttaa suoraan.",
      "Funktion tuloksen voi tallentaa muuttujaan. Ensin suoritetaan `square(6)`, ja sitten palautettu luku sijoitetaan muuttujaan `result`.",
      "Esittely `int triple(int value);` kertoo kääntäjälle nimen, parametrit ja tulostyypin etukäteen. Alempana oleva määrittely sisältää funktion rungon.",
      "`const std::string&` välittää merkkijonon kopioimatta ja estää funktiota muuttamasta sitä. Metodi `.size()` palauttaa merkkien määrän.",
      "Sisäkkäiset kutsut lasketaan sisältä ulospäin. Ensin `add(a, b)` palauttaa välisummaa, jonka jälkeen ulompi `add` lisää arvon `c`.",
      "Parametrien nimet selittävät tietojen merkityksen. Funktio saa arvot `total` ja `occupied`, ja `return total - occupied;` palauttaa vapaiden paikkojen määrän.",
    ],
    [
      "`int& alias = value;` luo viitteen eli toisen nimen samalle muuttujalle. Siksi `alias`-nimen kautta tehty muutos muuttaa heti myös `value`-arvoa.",
      "Parametri `int& value` vastaanottaa alkuperäisen muuttujan, ei kopiota. `++value` kasvattaa juuri `main`-funktiosta annettua arvoa.",
      "Vaihtamiseen tarvitaan väliaikainen `temp`, muuten ensimmäinen sijoitus hävittäisi yhden alkuperäisistä arvoista. Viitteet antavat funktion muuttaa molempia ulkoisia muuttujia.",
      "`int* ptr` esittelee osoittimen ja `&value` hakee muuttujan osoitteen. `ptr`-arvon tulostus näyttää osoitteen, ei siinä osoitteessa olevaa lukua.",
      "Valmiin osoittimen edessä oleva tähti tarkoittaa viittauksen purkamista. Lauseke `*ptr` hakee tallennetussa osoitteessa olevan arvon.",
      "Purettua osoitinta voi käyttää merkin `=` vasemmalla puolella. `*ptr = 25;` kirjoittaa uuden arvon suoraan siihen liittyvään `value`-muuttujaan.",
      "`nullptr` tarkoittaa, ettei osoitin osoita mihinkään. Sen purkaminen on vaarallista, joten ensin tarkistetaan `ptr != nullptr`.",
      "`const std::string&` välittää merkkijonon ilman kopiota ja suojaa sitä muutoksilta. Funktio saa lukea ja tulostaa tekstin, mutta ei muuttaa sitä.",
      "Taulukon nimi osoittaa ensimmäiseen alkioon. `ptr + 1` siirtyy toiseen alkioon, ja ulompi `*` hakee arvon uudesta osoitteesta.",
      "Argumentin ja parametrin nimet voivat olla erilaiset. `main`-funktion `passengers` muuttuu funktion sisällä viitteeksi `count`, mutta molemmat tarkoittavat samaa arvoa.",
    ],
    [
      "`class Greeter` luo uuden tyypin. `public:` avaa metodin ulkoiseen käyttöön, `g.sayHi()` kutsuu sitä pisteellä ja luokan sulkevan aaltosulkeen jälkeen tarvitaan `;`.",
      "`private:`-kohdan kenttää ei voi lukea suoraan `main`-funktiosta. Julkinen `speed() const` palauttaa arvon turvallisesti ja lupaa olla muuttamatta oliota.",
      "Konstruktorilla on sama nimi kuin luokalla eikä paluutyyppiä. Se suoritetaan automaattisesti, kun kirjoitetaan `Ride ride(24)`, ja se tallentaa parametrin kenttään.",
      "Alustuslista tulee kaksoispisteen jälkeen ennen konstruktorin runkoa. `seats_(seats)` luo kentän heti oikealla arvolla ja on parempi kuin myöhempi sijoitus.",
      "`capacity() const` on lukumetodi: se lukee yksityisen kentän ja palauttaa sen ulos. `const` kertoo, ettei lukeminen muuta oliota.",
      "Olio säilyttää tilansa kentässä `value_`. `increment()` muuttaa sitä ja `value() const` vain lukee, joten tieto ja toiminta ovat samassa luokassa.",
      "Asetusmetodi `setSpeed(int)` muuttaa yksityistä kenttää ja lukumetodi `speed() const` lukee sen. Näin luokka hallitsee oman tilansa käyttöä.",
      "Jokaisella oliolla on omat kenttänsä. Siksi `slow(10)` ja `fast(30)` säilyttävät eri nopeudet, vaikka molemmat ovat tyyppiä `Ride`.",
      "Konstruktori voi alustaa useita kenttiä pilkulla erotettuna. `area()` käyttää nykyisen olion arvoja `width_` ja `height_`.",
      "Täydessä luokassa järjestys on selkeä: julkinen konstruktori ja metodi, sitten yksityinen kenttä. Luokan määrittely päättyy merkkeihin `};`, ja olio käyttää julkista rajapintaa pisteellä.",
    ],
  ],
  en: [
    [
      "`std::cout` sends data to the console. The `<<` operator passes the value on its right into the output stream, double quotes mark text, and `;` ends the statement.",
      "Write the text inside the quotes exactly as it should appear. Capital letters and spaces inside a string are part of the output.",
      "`Score: ` is text, so it belongs inside double quotes. `10` is a numeric literal, so it has no quotes. Writing `\"10\"` would create text that cannot be used in normal numeric calculations. The second `<<` adds the number to the same output statement.",
      "The `\\n` sequence inside text is an escape sequence. It does not print the characters `\\` and `n`; it moves the output to a new line.",
      "Each `std::cout` command is a separate statement and needs its own `;`. C++ does not automatically place a space or new line between two statements.",
      "Writing `42` without quotes creates a number. Writing `\"42\"` creates two text characters, so a numeric value does not need quotes.",
      "The expression `2 + 3` is evaluated before it is printed, so `std::cout` receives the number `5`. Inside quotes, the program would print the characters `2 + 3` instead.",
      "Text and a number can be sent to one stream in sequence. Quote the text, leave the number unquoted, and place another `<<` before every additional item.",
      "`std::endl` is a special stream item, not text, so it needs no quotes. It starts a new line and immediately flushes the accumulated output to the console.",
      "A complete program needs `#include <iostream>` for `std::cout`, an `int main()` function, braces, and `return 0;`. Executable statements belong inside `main`.",
    ],
    [
      "`int age = 20;` creates a whole-number variable, names it, and gives it an initial value. Print `age` without quotes so the value is shown instead of the word.",
      "The `double` type stores decimal numbers. C++ uses a dot as the decimal separator, so write `4.5`, not `4,5`.",
      "The `bool` type stores only `true` or `false`. These are C++ values and are written in lowercase without quotes.",
      "`std::string` stores text, so the initial value `\"Alex\"` is quoted. The type needs `#include <string>`, while the variable name is printed without quotes.",
      "Write the type only when creating a variable. Later, `score = 15;` replaces its value; writing `int score` again would try to create another variable.",
      "The `const` keyword prevents a variable from changing after creation. Use it for values that must remain fixed.",
      "The expression `a + b` uses the values stored in both variables. C++ performs the addition first, then `std::cout` prints the result.",
      "If at least one division operand is a `double`, the result keeps its fractional part. Thus `10.0 / 4` gives `2.5`; dividing two `int` values would discard the fraction.",
      "The `+=` operator adds the right side to the current value and stores the result back. `points += 3;` means the same as `points = points + 3;`.",
      "The `*` operator multiplies values. When an `int` is multiplied by a `double`, C++ produces a decimal result so the fractional part is not lost.",
    ],
    [
      "`if` runs the block inside braces only when its condition is true. `>=` means greater than or equal to, and the condition belongs inside parentheses.",
      "The `else` block runs only when the `if` condition is false. The program therefore chooses exactly one of the two paths.",
      "The `==` operator compares two values. A single `=` assigns a new value instead, so an equality condition needs two equals signs.",
      "The `&&` operator means logical AND. The complete condition is `true` only when both the age and height conditions are true.",
      "The parentheses of a `for` loop contain three parts: the starting value, the continuation condition, and the counter change. Semicolons separate these parts.",
      "The counter starts at `0` and repeats while `i < 5`. The loop therefore uses `0, 1, 2, 3, 4`, but not `5`.",
      "A `while` loop checks its condition before every repetition. Increase the counter inside the loop, or the condition will stay true and create an infinite loop.",
      "The `sum` variable is an accumulator. On every repetition, `sum += i;` adds the next number to the total collected so far.",
      "`continue` immediately skips the rest of the current repetition. It does not end the loop; execution moves to the next counter value.",
      "The `--count` operator decreases the value by one. The condition `count >= 1` includes `3, 2, 1` and stops the loop before zero.",
    ],
    [
      "The `void` type means a function performs an action but returns no value. Empty `()` means there are no parameters, and `greet();` calls the function.",
      "The `std::string name` parameter receives text inside the function. At the call, `\"Alex\"` is a quoted string literal; inside the function, `name` is an unquoted variable.",
      "Writing `int` before the function name promises a whole-number result. `return number * 2;` calculates the value and sends it back to the call site.",
      "Separate parameters with commas and give every parameter a type. Arguments are supplied in the same order: the first enters `a`, the second enters `b`.",
      "A `bool` function must return `true` or `false`. The comparison `age >= 18` already produces such a Boolean value, so it can be returned directly.",
      "A function result can be stored in a variable. First `square(6)` runs, then its returned number is assigned to `result`.",
      "The declaration `int triple(int value);` tells the compiler the function name, parameters, and result type early. The later definition supplies its body.",
      "`const std::string&` passes a string without copying it and prevents the function from changing it. The `.size()` method returns the number of characters.",
      "Nested calls are evaluated from the inside out. First `add(a, b)` returns an intermediate sum, then the outer `add` adds `c`.",
      "Parameter names describe what the data means. The function receives `total` and `occupied`, and `return total - occupied;` returns the number of free seats.",
    ],
    [
      "`int& alias = value;` creates a reference, which is a second name for the same variable. Changing `alias` therefore changes `value` immediately.",
      "An `int& value` parameter receives the original variable instead of a copy. `++value` increases the exact value supplied from `main`.",
      "A swap needs temporary storage in `temp`; otherwise the first assignment would destroy one original value. References let the function change both outside variables.",
      "`int* ptr` declares a pointer, while `&value` obtains the variable's address. Printing `ptr` shows the address, not the number stored there.",
      "An asterisk before an existing pointer means dereference. The expression `*ptr` accesses the value stored at the saved address.",
      "A dereferenced pointer can appear on the left of `=`. The statement `*ptr = 25;` writes directly into the connected `value` variable.",
      "`nullptr` means a pointer refers to no object. Dereferencing it is unsafe, so first check the condition `ptr != nullptr`.",
      "`const std::string&` combines passing without a copy with protection from modification. The function may read and print the string but may not change it.",
      "An array name points to its first item. `ptr + 1` advances to the second item, and the outer `*` reads the value at that new address.",
      "An argument and a parameter may have different names. `passengers` from `main` becomes the reference `count` inside the function, but both names refer to one value.",
    ],
    [
      "`class Greeter` creates a new type. `public:` exposes the method, `g.sayHi()` calls it through a dot, and the class definition needs `;` after its closing brace.",
      "A field after `private:` cannot be read directly from `main`. The public `speed() const` method safely returns its value and promises not to modify the object.",
      "A constructor has the same name as its class and no result type. It runs automatically for `Ride ride(24)` and stores the supplied parameter in a field.",
      "An initializer list appears after a colon and before the constructor body. `seats_(seats)` creates the field with the right value immediately and is preferred to later assignment.",
      "The `capacity() const` method is a getter: it reads a private field and returns it to outside code. `const` shows that reading does not modify the object.",
      "An object stores state in `value_`. The `increment()` method changes it, while `value() const` only reads it, keeping data and actions together in the class.",
      "The `setSpeed(int)` setter changes the private field, while the `speed() const` getter reads it. This lets the class control access to its state.",
      "Every object has its own fields. Therefore `slow(10)` and `fast(30)` keep different speeds even though both objects use the same `Ride` type.",
      "A constructor can initialize several fields separated by commas. The `area()` method uses the current object's `width_` and `height_` values.",
      "A complete class keeps its public constructor and method before its private field. The definition ends with `};`, and objects use the public interface through a dot.",
    ],
  ],
  th: [
    [
      "`std::cout` ส่งข้อมูลไปยังคอนโซล ตัวดำเนินการ `<<` ส่งค่าด้านขวาเข้าสู่สตรีมเอาต์พุต อัญประกาศคู่ใช้กำหนดข้อความ และ `;` ใช้จบคำสั่ง",
      "เขียนข้อความภายในอัญประกาศให้ตรงกับผลลัพธ์ที่ต้องการ ตัวพิมพ์ใหญ่ ตัวพิมพ์เล็ก และช่องว่างภายในสตริงล้วนเป็นส่วนหนึ่งของผลลัพธ์",
      "`Score: ` เป็นข้อความจึงต้องอยู่ในอัญประกาศคู่ ส่วน `10` เป็นค่าตัวเลขจึงไม่ต้องมีอัญประกาศ ถ้าเขียน `\"10\"` จะกลายเป็นข้อความและไม่เหมาะกับการคำนวณตัวเลขตามปกติ ตัวดำเนินการ `<<` ตัวที่สองเพิ่มตัวเลขเข้าในคำสั่งแสดงผลเดียวกัน",
      "ลำดับ `\\n` ภายในข้อความเรียกว่า escape sequence มันไม่ได้แสดงตัวอักษร `\\` และ `n` แต่ย้ายผลลัพธ์ไปยังบรรทัดใหม่",
      "คำสั่ง `std::cout` แต่ละคำสั่งเป็น statement แยกกันและต้องมี `;` ของตัวเอง C++ จะไม่เติมช่องว่างหรือขึ้นบรรทัดใหม่ระหว่างสองคำสั่งให้อัตโนมัติ",
      "การเขียน `42` โดยไม่มีอัญประกาศสร้างค่าตัวเลข ส่วน `\"42\"` สร้างอักขระข้อความสองตัว ดังนั้นค่าตัวเลขจึงไม่ต้องใส่อัญประกาศ",
      "นิพจน์ `2 + 3` จะถูกคำนวณก่อนแสดงผล ดังนั้น `std::cout` จึงได้รับตัวเลข `5` ถ้าใส่ไว้ในอัญประกาศ โปรแกรมจะแสดงอักขระ `2 + 3` แทน",
      "ข้อความและตัวเลขสามารถส่งเข้าสู่สตรีมเดียวกันตามลำดับได้ ใส่อัญประกาศให้ข้อความ ไม่ใส่อัญประกาศให้ตัวเลข และวาง `<<` เพิ่มก่อนทุกรายการถัดไป",
      "`std::endl` เป็นรายการพิเศษของสตรีม ไม่ใช่ข้อความ จึงไม่ต้องใส่อัญประกาศ มันขึ้นบรรทัดใหม่และส่งข้อมูลที่สะสมไว้ออกไปยังคอนโซลทันที",
      "โปรแกรมที่สมบูรณ์ต้องมี `#include <iostream>` สำหรับ `std::cout` มีฟังก์ชัน `int main()` วงเล็บปีกกา และ `return 0;` คำสั่งที่ต้องทำงานต้องอยู่ภายใน `main`",
    ],
    [
      "`int age = 20;` สร้างตัวแปรจำนวนเต็ม ตั้งชื่อ และกำหนดค่าเริ่มต้น แสดง `age` โดยไม่ใส่อัญประกาศเพื่อให้เห็นค่าที่เก็บไว้แทนคำว่า age",
      "ชนิด `double` เก็บจำนวนทศนิยม C++ ใช้จุดเป็นตัวคั่นทศนิยม จึงต้องเขียน `4.5` ไม่ใช่ `4,5`",
      "ชนิด `bool` เก็บได้เพียง `true` หรือ `false` ค่าทั้งสองเป็นค่าของ C++ และต้องเขียนด้วยตัวพิมพ์เล็กโดยไม่มีอัญประกาศ",
      "`std::string` เก็บข้อความ ดังนั้นค่าเริ่มต้น `\"Alex\"` ต้องอยู่ในอัญประกาศ ชนิดนี้ต้องใช้ `#include <string>` ส่วนชื่อตัวแปรเวลาแสดงผลไม่ต้องใส่อัญประกาศ",
      "เขียนชนิดข้อมูลเฉพาะตอนสร้างตัวแปร ภายหลัง `score = 15;` จะเปลี่ยนค่าที่มีอยู่ แต่ถ้าเขียน `int score` อีกครั้งจะเป็นการพยายามสร้างตัวแปรใหม่",
      "คีย์เวิร์ด `const` ป้องกันไม่ให้เปลี่ยนค่าตัวแปรหลังจากสร้างแล้ว ใช้กับค่าที่ต้องคงเดิม",
      "นิพจน์ `a + b` ใช้ค่าที่เก็บอยู่ในตัวแปรทั้งสอง C++ บวกค่าก่อน แล้ว `std::cout` จึงแสดงผลลัพธ์",
      "ถ้าตัวตั้งหรือตัวหารอย่างน้อยหนึ่งค่าเป็น `double` ผลลัพธ์จะเก็บส่วนทศนิยมไว้ ดังนั้น `10.0 / 4` ได้ `2.5` แต่การหาร `int` สองค่าจะตัดส่วนทศนิยมทิ้ง",
      "ตัวดำเนินการ `+=` นำค่าด้านขวามาบวกกับค่าปัจจุบันแล้วบันทึกกลับ `points += 3;` มีความหมายเหมือน `points = points + 3;`",
      "ตัวดำเนินการ `*` ใช้คูณค่า เมื่อคูณ `int` กับ `double` C++ จะให้ผลลัพธ์เป็นทศนิยมเพื่อไม่ให้ส่วนทศนิยมหายไป",
    ],
    [
      "`if` จะทำบล็อกภายในวงเล็บปีกกาเมื่อเงื่อนไขเป็นจริงเท่านั้น `>=` หมายถึงมากกว่าหรือเท่ากับ และเงื่อนไขต้องอยู่ในวงเล็บกลม",
      "บล็อก `else` จะทำงานเมื่อเงื่อนไขของ `if` เป็นเท็จเท่านั้น โปรแกรมจึงเลือกทำเพียงหนึ่งในสองเส้นทาง",
      "ตัวดำเนินการ `==` ใช้เปรียบเทียบสองค่า ส่วน `=` เพียงตัวเดียวใช้กำหนดค่า ดังนั้นเงื่อนไขตรวจความเท่ากันต้องใช้เครื่องหมายเท่ากับสองตัว",
      "ตัวดำเนินการ `&&` หมายถึง AND ทางตรรกะ เงื่อนไขรวมจะเป็น `true` ก็ต่อเมื่อทั้งเงื่อนไขอายุและส่วนสูงเป็นจริง",
      "วงเล็บกลมของลูป `for` มีสามส่วน ได้แก่ ค่าเริ่มต้น เงื่อนไขทำต่อ และการเปลี่ยนตัวนับ โดยใช้เครื่องหมายอัฒภาคแยกแต่ละส่วน",
      "ตัวนับเริ่มที่ `0` และทำซ้ำขณะที่ `i < 5` ลูปจึงใช้ค่า `0, 1, 2, 3, 4` แต่ไม่ใช้ `5`",
      "ลูป `while` ตรวจเงื่อนไขก่อนการทำซ้ำทุกครั้ง ต้องเพิ่มค่าตัวนับภายในลูป มิฉะนั้นเงื่อนไขจะเป็นจริงตลอดและเกิดลูปไม่รู้จบ",
      "ตัวแปร `sum` เป็นตัวสะสม ในแต่ละรอบ `sum += i;` จะเพิ่มตัวเลขถัดไปเข้ากับยอดรวมที่สะสมไว้",
      "`continue` ข้ามคำสั่งที่เหลือของรอบปัจจุบันทันที แต่ไม่ได้จบลูป การทำงานจะไปยังค่าตัวนับรอบถัดไป",
      "ตัวดำเนินการ `--count` ลดค่าลงหนึ่ง เงื่อนไข `count >= 1` รวมค่า `3, 2, 1` และหยุดลูปก่อนถึงศูนย์",
    ],
    [
      "ชนิด `void` หมายถึงฟังก์ชันทำงานบางอย่างแต่ไม่คืนค่า วงเล็บ `()` ที่ว่างหมายถึงไม่มีพารามิเตอร์ และ `greet();` คือการเรียกฟังก์ชัน",
      "พารามิเตอร์ `std::string name` รับข้อความเข้ามาในฟังก์ชัน ตอนเรียกใช้ `\"Alex\"` เป็น string literal ที่มีอัญประกาศ ส่วนภายในฟังก์ชัน `name` เป็นตัวแปรจึงไม่มีอัญประกาศ",
      "การเขียน `int` หน้าชื่อฟังก์ชันเป็นการรับรองว่าจะคืนจำนวนเต็ม `return number * 2;` คำนวณค่าและส่งกลับไปยังจุดที่เรียกใช้",
      "คั่นพารามิเตอร์ด้วยเครื่องหมายจุลภาคและกำหนดชนิดให้ทุกพารามิเตอร์ อาร์กิวเมนต์ถูกส่งตามลำดับ ตัวแรกเข้า `a` และตัวที่สองเข้า `b`",
      "ฟังก์ชัน `bool` ต้องคืน `true` หรือ `false` การเปรียบเทียบ `age >= 18` ให้ค่าบูลีนอยู่แล้ว จึง return นิพจน์นี้ได้โดยตรง",
      "ผลลัพธ์ของฟังก์ชันเก็บไว้ในตัวแปรได้ ขั้นแรก `square(6)` ทำงาน แล้วตัวเลขที่คืนมาจึงถูกกำหนดให้ `result`",
      "การประกาศ `int triple(int value);` บอกชื่อฟังก์ชัน พารามิเตอร์ และชนิดผลลัพธ์แก่คอมไพเลอร์ล่วงหน้า ส่วนนิยามที่อยู่ภายหลังจะให้ตัวฟังก์ชันจริง",
      "`const std::string&` ส่งสตริงโดยไม่สร้างสำเนาและป้องกันไม่ให้ฟังก์ชันแก้ไขมัน เมธอด `.size()` คืนจำนวนอักขระ",
      "การเรียกฟังก์ชันซ้อนกันจะคำนวณจากด้านในออกด้านนอก ก่อนอื่น `add(a, b)` คืนผลบวกชั่วคราว แล้ว `add` ด้านนอกจึงนำ `c` มาบวกเพิ่ม",
      "ชื่อพารามิเตอร์บอกความหมายของข้อมูล ฟังก์ชันรับ `total` และ `occupied` แล้ว `return total - occupied;` คืนจำนวนที่นั่งว่าง",
    ],
    [
      "`int& alias = value;` สร้าง reference ซึ่งเป็นชื่อที่สองของตัวแปรเดิม การเปลี่ยน `alias` จึงเปลี่ยน `value` ทันที",
      "พารามิเตอร์ `int& value` รับตัวแปรต้นฉบับแทนสำเนา ดังนั้น `++value` จะเพิ่มค่าจริงที่ส่งมาจาก `main`",
      "การสลับค่าต้องมีที่เก็บชั่วคราวใน `temp` มิฉะนั้นการกำหนดค่าครั้งแรกจะทำลายค่าเดิมหนึ่งค่า reference ทำให้ฟังก์ชันแก้ตัวแปรภายนอกทั้งสองได้",
      "`int* ptr` ประกาศ pointer ส่วน `&value` อ่านที่อยู่ของตัวแปร การแสดง `ptr` จะแสดงที่อยู่ ไม่ใช่ตัวเลขที่เก็บอยู่ตรงนั้น",
      "เครื่องหมายดอกจันหน้าตัวแปร pointer ที่มีอยู่หมายถึงการ dereference นิพจน์ `*ptr` เข้าถึงค่าที่เก็บไว้ ณ ที่อยู่ดังกล่าว",
      "pointer ที่ dereference แล้วใช้ทางซ้ายของ `=` ได้ คำสั่ง `*ptr = 25;` เขียนค่าโดยตรงลงในตัวแปร `value` ที่เชื่อมอยู่",
      "`nullptr` หมายถึง pointer ไม่ได้ชี้ไปยังออบเจ็กต์ใด การ dereference จะไม่ปลอดภัย จึงต้องตรวจเงื่อนไข `ptr != nullptr` ก่อน",
      "`const std::string&` รวมการส่งค่าโดยไม่สร้างสำเนากับการป้องกันการแก้ไข ฟังก์ชันอ่านและแสดงสตริงได้แต่เปลี่ยนค่าไม่ได้",
      "ชื่ออาร์เรย์ชี้ไปยังสมาชิกตัวแรก `ptr + 1` เลื่อนไปยังสมาชิกตัวที่สอง และ `*` ด้านนอกอ่านค่าจากที่อยู่ใหม่นั้น",
      "อาร์กิวเมนต์และพารามิเตอร์อาจใช้ชื่อต่างกัน `passengers` จาก `main` กลายเป็น reference ชื่อ `count` ภายในฟังก์ชัน แต่ทั้งสองชื่อหมายถึงค่าเดียวกัน",
    ],
    [
      "`class Greeter` สร้างชนิดข้อมูลใหม่ `public:` เปิดเมธอดให้ภายนอกใช้ `g.sayHi()` เรียกเมธอดผ่านจุด และต้องมี `;` หลังวงเล็บปีกกาปิดของนิยามคลาส",
      "ฟิลด์หลัง `private:` ไม่สามารถอ่านโดยตรงจาก `main` เมธอด public `speed() const` คืนค่าอย่างปลอดภัยและรับรองว่าจะไม่เปลี่ยนออบเจ็กต์",
      "constructor มีชื่อเดียวกับคลาสและไม่มีชนิดผลลัพธ์ มันทำงานอัตโนมัติเมื่อเขียน `Ride ride(24)` และเก็บพารามิเตอร์ที่รับมาไว้ในฟิลด์",
      "initializer list อยู่หลังเครื่องหมายทวิภาคและก่อนตัวฟังก์ชัน constructor รูปแบบ `seats_(seats)` สร้างฟิลด์ด้วยค่าที่ถูกต้องทันทีและเหมาะกว่าการกำหนดค่าภายหลัง",
      "เมธอด `capacity() const` เป็น getter ซึ่งอ่านฟิลด์ private และคืนค่าให้โค้ดภายนอก ส่วน `const` แสดงว่าการอ่านนี้ไม่เปลี่ยนออบเจ็กต์",
      "ออบเจ็กต์เก็บสถานะใน `value_` เมธอด `increment()` เปลี่ยนค่า ส่วน `value() const` อ่านค่าเท่านั้น จึงรวมข้อมูลและการทำงานไว้ในคลาสเดียว",
      "setter `setSpeed(int)` เปลี่ยนฟิลด์ private ส่วน getter `speed() const` อ่านค่า วิธีนี้ทำให้คลาสควบคุมการเข้าถึงสถานะของตัวเอง",
      "ออบเจ็กต์แต่ละตัวมีฟิลด์ของตัวเอง ดังนั้น `slow(10)` และ `fast(30)` จึงเก็บความเร็วต่างกัน แม้ทั้งคู่จะใช้ชนิด `Ride` เหมือนกัน",
      "constructor กำหนดค่าเริ่มต้นให้หลายฟิลด์ได้โดยคั่นด้วยจุลภาค เมธอด `area()` ใช้ค่า `width_` และ `height_` ของออบเจ็กต์ปัจจุบัน",
      "คลาสที่สมบูรณ์จัดวาง constructor และเมธอด public ก่อนฟิลด์ private นิยามจบด้วย `};` และออบเจ็กต์ใช้อินเทอร์เฟซ public ผ่านเครื่องหมายจุด",
    ],
  ],
};
